### ISSUE TITLE
Links aus media auf Videos bei c3subtitles um die Untertitel zu verbessern

### ISSUE THREAD

**Issue by percidae** [voc/voctoweb#101]
Für Talks die auf c3subtitles.de vorhanden sind, wäre es schön, wenn das media Frontend auch Links zu der entsprechenden c3subtitles.de Seite anzeigen würde. User fänden so den direkten Weg um Untertitel zu erstellen und zu verbessern.

Am sinnvollsten wäre es vermutlich, wenn man das von der subtitles-VM per Skript über die API machen könnte.
Ein Aufruf mit der guid sowie der dazugehörigen Subtitles - URL wäre am einfachsten. Zusätzlich vielleicht noch die Möglichkeit über die guid und einen Befehl die URL auch löschen zu können.

Ein Workaround für die URL wäre auch möglich: Alle Talks vom 30c3, 31c3 und 32c3 welche auf c3subtitles nicht geblacklisted sind, sind auch aufrufbar über:
- www.c3subtitles.de/talk/guid/$guid
- www.c3subtitles.de/talk/frab-id/$frab-id

**Comment by saerdnaer** [comment]
@manno has_subtitles flag auf der conference?

**Comment by saerdnaer** [comment]
@percidae so?
<img width="828" alt="temp" src="https://cloud.githubusercontent.com/assets/40266/20034161/2bd1d050-a3b5-11e6-8c4e-e3ddf731c72d.png">

**Comment by percidae** [comment]
Das sieht gut aus.

Wo würde man denn dann ggf. die Steuerungsbuttons für den Player finden?

Eine zusätzliche Idee wäre es im Menü des CC-Auswahlknopf einen "Create"-Link einzubauen z.b. als untersten Punkt, zusätzlich zu der Sprachauswahl und "None".

**Comment by saerdnaer** [comment]
@percidae Das mit dem CC-Auswahlknopf ist eine gute Idee. Der Knopf ist allerdings leider erst da wenn auch Untertitel da sind. Druck dir doch mal das Mockup von Texec aus https://github.com/voc/voctoweb/issues/64#issuecomment-213950370 aus und zeichne ein wie du dir da die Untertitel-Integration vorstellst.

**Comment by MaZderMind** [comment]
@saerdnaer da fehlt mindestens noch etwas padding oben und unten, der Text klebt deutlich zu dicht am Video / an der Abschlusskannte. Add kleinschreiben wie edit würde es auch besser lesbar machen. An sich finde ich es da auch eher unglücklich platziert; ich würde den link dann in #64 unten, wo die subtitles zum download stehen verlinken.

**Comment by MaZderMind** [comment]
Alternativ könnte man auch, wenn es noch keine Subs gibt, einen CTA-Banner oder sowas oben hin tun, aber da würde ich @texec nochmal bemühen zu ;)

**Comment by MaZderMind** [comment]
in 4bbda4b hab ich einen generischen unter allen Talks Button eingefügt, bis mit @manno geklärt ist, wie wir subtitle-fähige Konferenzen auszeichnen wollen.

**Comment by saerdnaer** [comment]
@MaZderMind Das ist schon geklärt, war nur hier im Ticket nicht dokumentiert. Es gibt jetzt auf der conference ein Feld `metadata` das man für sowas hernehmen kann. In meiner lokalen DB steht da z.B. für den 32C3 folgendes drin
``` 
{
"subtiles": true
}
```
In https://github.com/voc/voctoweb/commit/2bee8b5b0ce12badc0573ba03630bbdb7ebc1ad9 sieht man exemplarisch wie man das dann in Ruby abfragen kann:
```
- if @conference.metadata['subtitles'].present?
   %a{href: 'https://www.c3subtitles.de/talk/guid/' +  @event.guid} Add or edit subtitles
```
