### ISSUE TITLE
Track User Agent for Recording View

### ISSUE THREAD

**Issue by manno** [voc/voctoweb#110]
We want to now how many users our apps have. The kodi app already calls the recording view API endpoint to register views. 
- Extend the RecordingView model with a user agent field
- `Public::RecordingsController.count` should store the agent

**Comment by manno** [comment]
@TobiX like that?

**Comment by TobiX** [comment]
Sounds sane to me.

Is the Apple TV app using the views API? Maybe @petershaw wants to comment on that?

**Comment by MaZderMind** [comment]
Also, we should track clicks on the Download-Links and count which formats are actually downloaded (for example if the audio-files are actually used)

**Comment by TobiX** [comment]
Is that something we should track in the frontend, then? Maybe we can create statistics from our mirror infrastructure? Can we push something like this into MirrorBrain/MirrorBits (whatever we'll be using in the future)

**Comment by TobiX** [comment]
@manno Since we talked about this yesterday: What is the state of this? Is media the right place for this? In light of #254, can we generate something like web server access logs and feed them into Matomo to easily get stats?

**Comment by manno** [comment]
@tobix yes, https://github.com/voc/voctoweb/blob/master/app/controllers/public/recordings_controller.rb#L19 stores the UA

**Comment by saerdnaer** [comment]
This issue is implemented, so we can close this ticket.
