### ISSUE TITLE
Developers Need Access to Live Data

### ISSUE THREAD

**Issue by manno** [voc/voctoweb#111]
Developers need access to the current database contents. We already consider most of it to be public.
 `capistrano deploy` should write a tarball with the fixtures to `public/`
- Create dump method to  exclude sensitive data, api keys, admin accounts and temporary tables like the recording views
- Create tarball and put below public
- Link the tarball from 'about'

**Comment by MaZderMind** [comment]
Wouldn't it be enough to have a task, which reads https://api.media.ccc.de/public/conferences and fills the development-system with real-world data that way?

**Comment by manno** [comment]
@MaZderMind no the public API should not be used to clone the database for a dev system.

**Comment by MaZderMind** [comment]
ok, we should then probably remove https://github.com/voc/voctoweb/blob/master/lib/tasks/db_import_conference.rake again. sorry for merging without speaking about it before.

So you're instead suggesting to modify to modify https://github.com/voc/voctoweb/blob/master/lib/tasks/db_dump_fixtures.rake instead, maybe adding an option, to leave out the aforementioned sensitive data and publish that instead? I'll open a PR for that then.

**Comment by MaZderMind** [comment]
Also we should ensure, that that after running `rake db:fixtures:load` the elasticsearch is also populated with data.

**Comment by MaZderMind** [comment]
fixed in 847af7c4eb5c01e80e1ca7772a43889ad5fc93ba
