### ISSUE TITLE
player: don't preload video file

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctoweb#114]
add preload=false to player

**Comment by MaZderMind** [comment]
@saerdnaer why do you think that not preloading would be a better idea then ie. preload=auto or preload=metadata?
See https://developer.mozilla.org/de/docs/Web/HTML/Element/video#attr-preload for reference.

**Comment by saerdnaer** [comment]
As far as I understand wie currently have no preload attribute, which is equivalent to preload=auto. My browser always downloads the whole file in full hd, even if i have not clicked the play button yet. Think about mobile internet etc. So probably preload=metadata is the right choice.

**Comment by MaZderMind** [comment]
@saerdnaer hast du mal den videoplayer mit preload="metadata" getestet? bei mir funktioniert mediaelement.js damit nicht mehr. preload="none" geht.

nur damit wir da klarheit haben: das tag definiert was passieren soll, *bevor* jemand auf den play-button klickt. dass der browser das video *nach* dem klick komplett runter lädt wird davon nicht beeinflusst.

**Comment by MaZderMind** [comment]
i reverted that in the above commit because it broke the player on chrome/linux

**Comment by saerdnaer** [comment]
Dann hatte ich es vermutlich nur in Safari/macOS getestet. Lass uns doch einfach  `preload="none"` nehmen.

**Comment by saerdnaer** [comment]
Wenn man `preload="none"` benutzt, funktioniert die vorschau beim timestamp link nicht mehr bzw. erst man auf den play button klickt. Ich würde jetzt nochmal `preload="none"` ausprobieren, zumindest bei meinem Chrome (unter macOS) funktioniert das.
