### ISSUE TITLE
"karussell" on frontpage broken if back button is used

### ISSUE THREAD

**Issue by derpeter** [voc/voctoweb#116]
Bug: Pictures in the Karussell getting vertical staged 

Reproduce: 

1. go on media.ccc.de
2. use the "right arrow" in the Karussell
3. click on a talk
4. use the back button to get back to the start page

tested with chromium on linux

**Comment by derpeter** [comment]
I'm not sure if the behavior has changed but now it happens also when you go back to the start page without using the karussell at all

**Comment by MaZderMind** [comment]
I guess this broke with the rails 5 / turboinks 5 upgrade: http://stackoverflow.com/a/18770589
fix incoming

**Comment by MaZderMind** [comment]
the karussell is still broken, but in another way:
upon each forward-backward to the startpage, the slider is moved down and paging arrows appear.
