### ISSUE TITLE
Feature request: playlists button in list view

### ISSUE THREAD

**Issue by rixx** [voc/voctoweb#118]
Sometimes there are events with a lot of very short videos ([example](https://media.ccc.de/c/jh16?sort=date)) where watching all of the videos is kind of annoying because you have to switch back to the list view all the time.

Being able to automatically to watch all videos in an event or a category would be great (via a "Play all" button in the list view?).

**Comment by saerdnaer** [comment]
Nice idea. Our player has already support for playlists... Can your send us a pull request?
