### ISSUE TITLE
Cluster conferences

### ISSUE THREAD

**Issue by Matthias84** [voc/voctoweb#12]
There are currently [some conferences](https://media.ccc.de/b/conferences), which aren't clustered yet:
* sigint
* easterhegg
* ccccamp

**Comment by manno** [comment]
Personally I dislike 'clustering'. Especially if folders only contain one conference. I'd rather not build a deeply nested navigation tree. Additionally, everything we change now will lead to even more broken links. Well, with the new URL scheme at least the event video links stay intact.

I'd close this issue, but if we want to change the folders: I'd like to 'de-cluster' the navigation.

**Comment by Matthias84** [comment]
I agree that nesting isn't that nice, but all of the mentioned conferences have >1 event and IMHO clutter the conferences landing page
