### ISSUE TITLE
tag view layout overlaps text

### ISSUE THREAD

**Issue by derpeter** [voc/voctoweb#121]
If the tag view is used the title of the events overlaps with the date.
https://media.ccc.de/tags/Das%20ist%20Netzpolitik!

**Comment by MaZderMind** [comment]
![screenshot from 2016-10-23 23-56-06](https://cloud.githubusercontent.com/assets/142237/19629777/4e1ad4ce-997c-11e6-86e6-1ee3e9943869.png)
