### ISSUE TITLE
Fullscreen Window is offset in Chrome and Opera

### ISSUE THREAD

**Issue by TheSebware** [voc/voctoweb#138]
When I use Chrome or Opera to view a recording in fullscreen mode, the player is offset by guessed 10% to the left.

OS: Windows 7 Pro amd64
Browser: Chrome 54.0.2840.71 m (amd64) and Opera 41.0.2353.46

**Comment by njrl** [comment]
Ack, here too..
os: lubuntu 16
browser chrome 50.0.2661.102  and chromium 53.0.2785.143

in firefox it seems ok

**Comment by TheSebware** [comment]
When do you roll out your code changes, as this bug is still occuring?

**Comment by MaZderMind** [comment]
At some point im time between now and congress ;)
For the time being: use vlc or another desktop player.
