### ISSUE TITLE
years as tags

### ISSUE THREAD

**Issue by Matthias84** [voc/voctoweb#14]
Currently the videos / conferences [aren't tagged](https://media.ccc.de/tags) with a year, so we can't filter for all content of a single year.

**Comment by derpeter** [comment]
This is a good idea but not realy a bug as the tag can just be added.
But a way to automated this would be nice.

**Comment by saerdnaer** [comment]
@manno: can you add the a year tag to the 'old' content based on the recording date directly in the database via an SQL query? For talks without an recording date we should be able to interpolate the year from the congress number.

**Comment by saerdnaer** [comment]
shoud be implemented
