### ISSUE TITLE
Redesign Promoted-Slider on Startpage

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctoweb#147]
According to @jjeising's Review in #145 the promoted-Slider on the Startpage should be redesigned to give more context and remove the blue-ish background which originates from the long-gone 30C3 design.

This task is separate from the structural changes handled in #145 and require more preparation, for example a new background image is needed. These new changes are handled in this ticket

See the relevant comments in this image for details:
![notes](https://cloud.githubusercontent.com/assets/40333/20819860/7db3df08-b837-11e6-98bd-038c1c9ad2f1.png)

**Comment by MaZderMind** [comment]
Also, the paging-buttons overlap with long titles:
![screenshot_from_2016-12-09_10-38-42-s5b3kuvb](https://cloud.githubusercontent.com/assets/142237/21046003/d6f1fdb8-be02-11e6-8046-144fdf29e66c.png)

**Comment by meise** [comment]
Won't fix.
