### ISSUE TITLE
search results are missing conference 

### ISSUE THREAD

**Issue by derpeter** [voc/voctoweb#152]
e.g. https://media.ccc.de/search/?q=fefe  misses the information to which conference the result belongs in a very similar view https://media.ccc.de/popular this information is available. 
It might also be a good idea to move the conference name to the right to the other metadata and make it clickable.

**Comment by MaZderMind** [comment]
the placement of the conference (actually: the whole list-view) needs some re-thinking by a designer. I'll try to arrange this in january. For the time being i'll close this Issue with the other ideas implemented.
