### ISSUE TITLE
Show sum of Hours on Startage

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctoweb#154]
Together with Number of Files, Videos and Conferences

**Comment by blinry** [comment]
By the way, using a dot as a delimiter could be confusing to English-speaking persons. We could switch to a  small space, as recommended by [ISO 31-0](https://en.wikipedia.org/wiki/ISO_31-0#Numbers)?

**Comment by blinry** [comment]
Oh, and another thing: I decided to sum up the *events'* durations, not those of all available recordings. The former seems more sensible to me, as nobody would watch all formats or language versions of an event.

**Comment by MaZderMind** [comment]
I don't know about the 1000er separator, but if you think it would be better please open a PR.

**Comment by blinry** [comment]
The pull request for small spaces is still open, but this issue can be closed.
