### ISSUE TITLE
MediaElementJs does not correctly initialize for some old videos

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctoweb#156]
When accessing a Player-Page referencing a missing video file or referencing a Video-File that is not playable in the browser (for example https://media.ccc.de/v/1110), mediaelementjs fails to initialize. This renders the player page into an unsuable mess:

![screencapture-media-ccc-de-v-1009-1481984292939](https://cloud.githubusercontent.com/assets/142237/21287464/4f7e8976-c46c-11e6-8afa-fad3aab56db1.png)

**Comment by saerdnaer** [comment]
@MaZderMind The page you linked, works for me as of today. Was this issue fixed or does it still persist?

**Comment by saerdnaer** [comment]
problem low longer exists
