### ISSUE TITLE
JSON-Api caches events

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctoweb#163]
[[master/app/helpers/public_json_helper.rb#L8]] caches json results only based on their modified-timestamp. This can lead to impropper results.

Details have be díscussed in IRC. This is a placeholder to track the Status of this issue.

**Comment by dedeibel** [comment]
Cache key is currently only built from the object type and update dates of the provided objects. This is goes well for a lot of cases but not always.
The id should be taken into account here too.

**Comment by manno** [comment]
https://github.com/voc/voctoweb/commit/6ba5b7f8f49d96a7ce5eb573500740b3dc9c22c0
