### ISSUE TITLE
Optimize Search-Result Order

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctoweb#165]
The Search-Result ordering is unexpected:
https://media.ccc.de/search/?q=security+nightmares

I'd expect to have at least the last 3 years as the top-3 results, probably completely sorted by date.

![screenshot from 2016-12-21 00-24-12](https://cloud.githubusercontent.com/assets/142237/21371843/d764ef0c-c713-11e6-829f-d13bdfb96798.png)

**Comment by rixx** [comment]
Seems fixed.
![screenshot_2018-05-29 media ccc de - search for security nightmares](https://user-images.githubusercontent.com/2657547/40631206-b289dc38-62da-11e8-8997-b23d0dbddc96.png)
