### ISSUE TITLE
torrent avaible?

### ISSUE THREAD

**Issue by MUHeinz** [voc/voctoweb#166]
On https://media.ccc.de/news.atom:
> Torrents
> 10.05.2014 15:31
> The new CDN allows us to serve torrents for all the videos. Torrent links have been added to all video pages.
> 
Am I to blind to find it for example for
https://media.ccc.de/v/fiffkon16-4020-10_jahre_informationsfreiheitsgesetz_wie_wir_den_staat_zu_mehr_transparenz_zwingen
?
or is it still under construction?
or is it already dead?
Thanks

**Comment by saerdnaer** [comment]
related: #32

**Comment by manno** [comment]
Currently you can just append `.torrent` to the links: http://cdn.media.ccc.de/events/fiffkon/2016/h264-hd/fiffkon16-4020-deu-10_Jahre_Informationsfreiheitsgesetz_-_Wie_wir_den_Staat_zu_mehr_Transparenz_zwingen_hd.mp4.torrent

This will change in the future, when we move to mirrorbit. That's probably why the links are not included in the new download page design (@mazdermind?) 
There are some ideas how to handle torrents afterwards, but I'm not involved there.

**Comment by MaZderMind** [comment]
Hm, I think i just forgot to add them; they are in the design in #64.

On the other hand, there is afaik still no solution for re-releasing torrents. We will have to re-release files that are broken or incomplete and this will kill all existing swarms around the torrents.

Also, we have enough of bandwidth on the http-servers available, so making torrents avaiable is not helping us, it's just adding another system to maintain, so I don't know if we really want to promote them or not.

I'll see if I can add the buttons back to the ui before congress.

**Comment by MaZderMind** [comment]
I added the buttons and deployed the changes: https://media.ccc.de/v/32c3-7546-security_nightmares_0x10

have fun.
