### ISSUE TITLE
"Unexpected input" error in /33c3/gen/main.css

### ISSUE THREAD

**Issue by al--** [voc/voctoweb#173]
https://streaming.media.ccc.de/33c3/gen/main.css

And maybe report to @C3VOC that you've seen this error:

exception 'Less_Exception_Chunk' with message 'ParseError: Unexpected input in main.less on line 174, column 39
172| }
173| 
174| .overview .room-group-live-music .room. .panel .panel-body,
175| .overview .room-group-live-music .room. .panel .panel-body {
176| 	margin-bottom: 0;
177| }' in /srv/nginx/streaming-website/lib/less.php/Less.php:543
Stack trace:
#0 /srv/nginx/streaming-website/lib/less.php/Less.php(487): Less_Parser->GetRules('/srv/nginx/stre...')
#1 /srv/nginx/streaming-website/lib/less.php/Less.php(364): Less_Parser->_parse('/srv/nginx/stre...')
#2 /srv/nginx/streaming-website/lib/less.php/Cache.php(167): Less_Parser->parseFile('configs/confere...', '../../configs/c...')
#3 /srv/nginx/streaming-website/lib/less.php/Cache.php(106): Less_Cache::Cache(Array, Array)
#4 /srv/nginx/streaming-website/lib/helper.php(71): Less_Cache::Get(Array, Array)
#5 /srv/nginx/streaming-website/index.php(212): handle_lesscss_request('configs/confere...', '../../configs/c...')
#6 {main}

**Comment by manno** [comment]
Streaming is not handled by voctoweb.
