### ISSUE TITLE
Transmission torrent client 

### ISSUE THREAD

**Issue by corvancrowing** [voc/voctoweb#174]
Hey,

I get this error inside of Transmission:

![bildschirmfoto_2016-12-28_16-51-50](https://cloud.githubusercontent.com/assets/24680473/21525483/d6f75cd4-cd1d-11e6-8260-adc4dc3371e2.png)

Transmission has no Problems with another Mirror, so it is not really a problem for me, but I thought I'd give this as feedback. If this is intended, please consider this issue as invalid

**Comment by manno** [comment]
I think this has been fixed
