### ISSUE TITLE
Mobile UI: feedMenu mit rss-Links optimieren

### ISSUE THREAD

**Issue by hejjoe** [voc/voctoweb#176]
Die Links zu den Podcast-Feeds sind im mobilen UI leider nicht anklickbar. Ist eine mittige Ausrichtung des Menüs möglich?
Screenshot mit iOS-Device:
![qdgutqc](https://cloud.githubusercontent.com/assets/142237/21582371/ca6ef802-d054-11e6-8513-a210a2482014.png)

**Comment by dedeibel** [comment]
Fixed in #201
