### ISSUE TITLE
Embedded Streams aren't https

### ISSUE THREAD

**Issue by kaffeeringe** [voc/voctoweb#181]
Hi!

I used the embed-Code from media.ccc.de to include a video into a blogpost. The iframe is loaded via https but the included streams are not. Thus it's mixed content and the address field in the browser is not green: https://kaffeeringe.de/5257/was-man-aus-meta-daten-lesen-kann/

**Comment by manno** [comment]
https://media.ccc.de/about.html - Privacy Policy

**Comment by kaffeeringe** [comment]
"These files are served via HTTP, without encryption, due to technical issues." Okay... ;-)
