### ISSUE TITLE
Satzbau Startseite

### ISSUE THREAD

**Issue by royrobotiks** [voc/voctoweb#182]
Der folgende Satz auf der Startseite funktioniert so nicht: "Pünktlich zum Congress hat media.ccc.de ein Facelifting bekommen und präsentiert sich mit einer neu gestalteten Startseite sowie einer überarbeiteten Download-Sektion**en bekommen.**"

Abgesehen davon ist alles schick!

**Comment by MaZderMind** [comment]
thx, fixed
