### ISSUE TITLE
Some Torrents responded with 404 during the event

### ISSUE THREAD

**Issue by gituser72** [voc/voctoweb#186]
Hello all,

ex. the download of the torrent http://cdn.media.ccc.de/congress/2016/h264-hd/33c3-8221-eng-deu-spa-Genetic_Codes_and_what_they_tell_us_-_and_everyone_else_hd.mp4.torrent isn't working (from the late evening 2016-12-30 on) although http://cdn.media.ccc.de/congress/2016/h264-hd/33c3-8438-eng-deu-fra-No_Love_for_the_US_Gov_hd.mp4.torrent worked 2016-12-31 at 23:08.

**Comment by MaZderMind** [comment]
@gituser72 thank you for your report. Where did you take the URLs from?
The URLs seem to work now so it might have been a timing-issue.

When the File is completely uploaded to the CDN it will be visible in media.ccc.de (with a download-link for the torrent), even if the torrent might not have been generated completely.

@meise do you know how mirrorbrain behaves when a new file is added and shortly after the torrent is requested?

**Comment by dedeibel** [comment]
Other files of the recording where also affected. After a couple of ten minutes everything was present.

**Comment by manno** [comment]
This is not related to the rails app.

**Comment by gituser72** [comment]
Hello Peter,

just got your mail. Thanks. Just saw that the issue is closed by now.

But to answer your question: I took them all from your site, no third 
party involved.


Am 01.01.2017 um 19:06 schrieb Peter:
