### ISSUE TITLE
Torrent-RSS Responds with 500 Internal Server Error

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctoweb#187]
The URL https://media.ccc.de/c/33c3/podcast/torrent.xml currently responds with 500 Internal Server Error.

**Comment by MaZderMind** [comment]
@manno but it shouldn't respond with a 500 anyway, better with a 404 then.

**Comment by SuperSandro2000** [comment]
> This is not a valid URL and I still want to remove all torrent support from media.ccc.de

What where the reasons for that?

**Comment by a-tze** [comment]
Without seeders, it won't work at all, with web seeding it DOSes the CDN mirrors and does basically a HTTP download that you could have achieved in a simpler way.
