### ISSUE TITLE
Frontend Player: HD/SD quality toggle does not work

### ISSUE THREAD

**Issue by agnat** [voc/voctoweb#189]
Looking at [33c3 footage](https://media.ccc.de/v/33c3-8021-eine_kleine_geschichte_der_parlamentsschlagerei) the embedded player (MediaElement.js, I believe) has a "Source Chooser" control (the star icon thingy):

![screen shot 2017-01-02 at 23 01 02](https://cloud.githubusercontent.com/assets/137545/21596760/f31ab534-d13f-11e6-9af3-5a8b428054f1.png)

I'd expect it to toggle HD/SD playback, but it doesn't seem to work.

**Comment by manno** [comment]
@MaZderMind I think the new player broke the source chooser. There was a custom  modification to the `adjustSourcechooserBox` function and some styling which might not work anymore. Can you take a look?
