### ISSUE TITLE
HTTPS only option

### ISSUE THREAD

**Issue by derpeter** [voc/voctoweb#191]
Currently the page is delivered via HTTPS but not all mirros provide korrekt HTTPS wich ends up in mixed content warnings. This is also true for the embed link. As we got now more bandwith for our own CDN nodes we should think of an (maybe opt in) way to allow people to get only get content from HTTPs mirrors or only from our own mirrors. This is also a privacy thing as we don't know what the mirrors store on meta data.

**Comment by manno** [comment]
We would need to store a cookie to remember the choice. Maybe the existing html5 source fix at https://github.com/voc/voctoweb/blob/master/app/assets/javascripts/mirrorbrain-fix.js#L1 could be extended to delete all external (=non ssl) mirrors then.

**Comment by saerdnaer** [comment]
We have only https mirros now
