### ISSUE TITLE
UI: German Text in News Section -> 33C3 Facelifting

### ISSUE THREAD

**Issue by CheesekK** [voc/voctoweb#192]
Pünktlich zum Congress hat media.ccc.de ein Facelifting bekommen und präsentiert sich mit einer neu gestalteten Startseite sowie einer überarbeiteten Download-Sektion **bekommen**."

... There is a "**bekommen**" which doesn't belong there. 

![image](https://cloud.githubusercontent.com/assets/12976562/21590966/593b200a-d100-11e6-9918-ca80c0da3d52.png)

**Comment by saerdnaer** [comment]
fixed
