### ISSUE TITLE
Podcast Feed: videos contain only one audio-track

### ISSUE THREAD

**Issue by manuelhaussmann** [voc/voctoweb#195]
The podcast feed (https://media.ccc.de/podcast.xml) has for many (all?) talks of the recent 33c3 only mp4 files with a single audio track, instead of all of them.

**Comment by hwhw** [comment]
The language of the audiotrack included is also in many (all? some?) cases not the original language of the talk.

**Comment by saerdnaer** [comment]
works now as intented

**Comment by florian-reus** [comment]
Hi,
can you point out how it's intended?
Both in NewPipe (selected the media.ccc source) and Android Podcast Addict I can only find the tranlated english stream. Even the (not linked on the site) master feed shows only one audio track: https://media.ccc.de/c/37c3/podcast/mp4-master.xml
Wrong apps?
