### ISSUE TITLE
Make conference view sortable by view count

### ISSUE THREAD

**Issue by blinry** [voc/voctoweb#196]
I'd like to be able to sort a view like https://media.ccc.de/c/33c3 descendingly by view count, to get a feeling of which talks are popular. Is this a wanted functionality?

It seems to me it's just a matter of adding a view_count desc entry to the SORT_PARAM hash in the ConferencesController, and exposing sort buttons in the view. If you want, I can put together a PR, if you give me an "okay", but it's probably much easier if one of you, who has a functioning test setup does it. Thanks! :)

**Comment by dedeibel** [comment]
The view count is currently not displayed it would also have to be added somewhere.

Seems to me like it is more a question of whether to keep the UI simple or add more information. Where to stop?

As for the test setup: If you are really interested you should have a working setup in minutes by running vagrant up and calling http://media.ccc.vm:3000 (ignoring sudo and missing virtualbox dependency issues)

**Comment by blinry** [comment]
I share your concerns regarding a cluttered interface. Even though, the view count is the only information from "above the line" in the event view that is not displayed in the conference view. Could go between the date and the presenters' names?

**Comment by derpeter** [comment]
this seems to be two different things. Showing the play count in the overview may or may not cluttering the UI but sorting by it only adds one sting to the top bar

**Comment by blinry** [comment]
That's true, but I also agree to @dedeibel that it makes little sense to be able to sort by view count if this number is not displayed anywhere. Those two additions should go hand-in-hand.

So, how do we decide whether or not this would be a good idea? :)

**Comment by rohieb** [comment]
An option would be to show the view count only when the view is being sorted by view count.

**Comment by derpeter** [comment]
I think the view count is important enough to show it in all views.

**Comment by Valodim** [comment]
I'd like to offer a different point of view: Just because those features share some code doesn't mean they can't be added independently. In fact, not displaying a view count to keep the focus on content and not clutter the view is a perfectly valid UX choice in my eyes, regardless of a "sort by popularity" feature.  :)

**Comment by MaZderMind** [comment]
I'd go on and add the View-Count to both:
````
<li class="count">
<span class="icon icon-hashtag"></span>
2342
</li>
````

![bildschirmfoto 2017-01-17 um 10 57 15](https://cloud.githubusercontent.com/assets/142237/22015789/c027fa8c-dca3-11e6-8c4e-70cd47d2f502.png)

PR welcome :)

**Comment by dedeibel** [comment]
Just remembered, there is already an "eye" icon used on the player page

![eye](https://cloud.githubusercontent.com/assets/26708/22033918/c4c06934-dcea-11e6-934c-ca908e4aa4d3.png)

**Comment by blinry** [comment]
Thanks for mentioning the vagrant setup, @dedeibel! It was super-easy to get this to work!
