### ISSUE TITLE
Torrent links missing

### ISSUE THREAD

**Issue by mark-orion** [voc/voctoweb#197]
I just "came back" to continue downloading videos from 33c3 and there are no torrents anymore. Only the direct download from http://ftp.halifax.rwth-aachen.de is available.
Please put them back in. Torrent downloads save you bandwidth and give me speed!

**Comment by mark-orion** [comment]
Just got a reply via Twitter that explain the situation:
We switched CDN frontends. The old frontends' torrent handling had too many issues. We are looking into finding a replacement.

**Comment by MUHeinz** [comment]
I see there are no torrents available
On my System are 143 torrents running with 33c3
If some of the files needed i can post them here
newer Videos I create a torrent and seed them via ThePirateBay.org
