### ISSUE TITLE
Metadata-Field in Backend not editable

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctoweb#198]
![screencapture-media-ccc-de-admin-conferences-101-edit-1484082403196](https://cloud.githubusercontent.com/assets/142237/21824765/270001be-d781-11e6-9a7a-13cabe9f8c16.png)

**Comment by manno** [comment]
No, this never worked: https://github.com/voc/voctoweb/commit/17903b9925f9d110e6f18eac9e0f057d6b1760c8
 
You can still use the private API to read an set metadata. Adding these to active admin does not work out of the box. By default it turns the  hash into a string while saving.

**Comment by saerdnaer** [comment]
In my local instance I was able to edit de field.

**Comment by saerdnaer** [comment]
fixed
