### ISSUE TITLE
Player doesn't load in Vivaldi browser, possible inaccurate media feature detection

### ISSUE THREAD

**Issue by pegro** [voc/voctoweb#199]
I use Vivaldi Browser 1.6.689.46 (Stable channel) (64-bit) on Linux.
When I visit e.g. https://media.ccc.de/v/33c3-8439-durchmarsch_von_rechts I only see the poster image instead of a player. Developer console contains no error messages.
The default video file loaded is a MP4 with H264 codec and I suspect my browser is not able to decode that. See attached screenshot from http://demos.flowplayer.org/videotest/canplay.html ![snap0003](https://cloud.githubusercontent.com/assets/4572112/21865315/e47ff9d2-d845-11e6-9723-0fb86f67e100.png)

Maybe in that case, the page should try to play the webm version or show an error message.

**Comment by pegro** [comment]
As a workaround for vivaldi users: install libffmpeg.so like described here:
https://gist.github.com/ruario/bec42d156d30affef655

For me, downloading http://repo.herecura.eu/herecura/x86_64/vivaldi-snapshot-ffmpeg-codecs-55.0.2883.76-1-x86_64.pkg.tar.xz and extracting it to /opt/vivaldi/lib helped. Now I get a player.

But the issue, when the browser is not able to play the codec, remains.

**Comment by saerdnaer** [comment]
please reopen if this issue is still persists.
