### ISSUE TITLE
SD Podcast Feed

### ISSUE THREAD

**Issue by wirew0rm** [voc/voctoweb#201]
Is there a low quality version of the podcast feeds available?

**Comment by dedeibel** [comment]
You mean of this feed? https://media.ccc.de/podcast.xml

Currently not, but an SD feed could be added I guess. I would expect for mobile use in a podcast app?

**Comment by wirew0rm** [comment]
More precisely I would like to have this one in SD:
https://media.ccc.de/c/33c3/podcast/mp4.xml

You're correct about the usecase, I'm studying abroad without a unmetered line, also space on (cheap) mobile devices is still very limited and on the small screen I can live with SD quality.

In general i think it's a problem of podcasts that you have to provide a seperate feed for each format, would be much nicer if it could be selected by the client, but I've looked around and it doesn't seem to be possible in the current podcast formats.

**Comment by dedeibel** [comment]
Hi @manno - I thought the usecase is quite legit and experimented with sd feeds.

In my branch I changed the navigation dropdown to a two column element that will have the SD version optionally in the second column. It would be cool if you could have a look at it and see if it is a good idea. Code should be cleaned up a bit more before going on.

Main Page:

![feeds-main-page](https://cloud.githubusercontent.com/assets/26708/21964904/0ab812da-db55-11e6-8708-b3a811205ef3.png)

Conference Page:

![feeds-event](https://cloud.githubusercontent.com/assets/26708/21964903/0ab7c6a4-db55-11e6-8f1b-994196aa6369.png)

There are tooltips set for the "SD Quality" entries, in case someone is wondering what it does.

https://github.com/voc/voctoweb/compare/master...dedeibel:sd_podcast_stream

It seems to me the backend side should be fine providing a differently filtered set of feeds. My solution for the podcast.xml is currently based on copy'n'paste but I think we should be able to pass in a filter function or something.
