### ISSUE TITLE
Undefined language "eng-deu-fra"

### ISSUE THREAD

**Issue by johnjohndoe** [voc/voctoweb#204]
I noticed that the API returns `"eng-deu-fra"` as a language value.
This string is currently not defined in `LANGUAGES` in [lib/languages.rb](https://github.com/voc/voctoweb/blob/master/lib/languages.rb).
Can you please confirm?

**Comment by dedeibel** [comment]
What exactly is the problem you are experiencing?

Files like http://cdn.media.ccc.de/congress/2016/webm-sd/33c3-7811-deu-eng-fra-Irren_ist_staatlich_webm-sd.webm of https://media.ccc.de/v/33c3-7811-irren_ist_staatlich contain multiple audio tracks. You can split the given language string by "-" to get each single language key.

**Comment by johnjohndoe** [comment]
Ah, multiple audio tracks. That makes sense.
Can you please defined a language type for the multi audio?

> What exactly is the problem you are experiencing?

I am working on a [library for the API](https://twitter.com/d3rp3t3r/status/803190625998934016). There, I noticed that `"eng-deu-fra"` was not defined as a language type.

**Comment by dedeibel** [comment]
I don't think this will happen, the language class represents single languages.
It is also used to determine the main and singular language of an event. The languages of a recording, separated by "-", are also validated against the languages.

**Comment by johnjohndoe** [comment]
Can you please point me to the location in code where this is done? Maybe this helps me to adapt in the library.

**Comment by dedeibel** [comment]
Sure. See https://github.com/voc/voctoweb/blob/master/app/models/recording.rb#L90 and line 98.

**Comment by dedeibel** [comment]
@johnjohndoe  Is this done then for now? If so, please close.

**Comment by johnjohndoe** [comment]
@dedeibel Sorry for the silence. Just the usual week work stress stops me from giving attention to side projects.

Please confirm / deny:
As a user of the API I can expect that the value of a `"*language*"` property will be
- either a single language, e.g. `"fra"`
- or multiple languages separated by dashes, e.g. `"eng-deu-fra"`
- and all individual language values are defined in the [`LANGUAGES`](https://github.com/voc/voctoweb/blob/master/lib/languages.rb#L2) type

**Comment by dedeibel** [comment]
Sounds good but I personally can't guarantee for that, your client should not totally crash because of any mismatch imho. 

The current validation enforces what you mentioned above.

I used the api to list all recording languages, this is what I found

```
   2648 "deu"
    175 "deu-eng"
     48 "deu-eng-fra"
     12 "deu-eng-gsw"
      4 "deu-eng-spa"
  10493 "eng"
    675 "eng-deu"
    159 "eng-deu-fra"
     20 "eng-deu-rus"
     16 "eng-deu-spa"
     52 "fra"
      3 "gsw"
      5 "rus"
      6 "spa"
```

**Comment by johnjohndoe** [comment]
Thanks for the confirmation. Yes, I covered unknown language strings as well. I think I will start like that then.

**Comment by johnjohndoe** [comment]
Here is the library I develop: [c3media-base](https://github.com/johnjohndoe/c3media-base)
