### ISSUE TITLE
30c3 guids differ from the ones in the fahrplan schedule.xml

### ISSUE THREAD

**Issue by percidae** [voc/voctoweb#208]
Currently the database of media has different guids for 30c3 than the fahrplan schedule.xml.
This causes two issues:

- The links from the talk to c3subtitles.de depend on the guid from the fahrplan. These links are all broken at the moment.

-  c3subtitles.de announces via the media api with the guid as key to the media frontend, where to find which subtitle language to display them in the download section and in the webplayer. This is currently not possible to do via API since the guids don't match.

Possible solution:
Change the guids from 30c3 in the media database to those which were used in the fahrplan which can be found here: [30c3 Fahrplan](https://events.ccc.de/congress/2013/Fahrplan/)

**Comment by manno** [comment]
Ok, I was able to update all guids in 30c3
