### ISSUE TITLE
Subtitle Download Button changes position

### ISSUE THREAD

**Issue by percidae** [voc/voctoweb#209]
The subtitle download button usually seems to stick to the left, like for the [32c3 opening](https://media.ccc.de/v/32c3-7550-opening_event).
Visible in this screenshot:
![32c3_opening_subtitle_download_button](https://cloud.githubusercontent.com/assets/5713994/22110630/ad77feb8-de5c-11e6-8ab6-60966b06ed28.jpg)

For the [33c3 closing](https://media.ccc.de/v/33c3-8428-33c3_closing_ceremony) it moves to the right and very close to the text, which looks odd:
![33c3_closing_subtitle_download_button](https://cloud.githubusercontent.com/assets/5713994/22110636/b3cb18a4-de5c-11e6-86cb-eb05edac60cd.jpg)

**Comment by MaZderMind** [comment]
The difference is, that on the Opening the Subtitles-Button opens a Flyout to select one of the multiple Languages, while on the Closing it links directly to the .srt.

Nevertheless, the placement in the closing-View is a bug.
