### ISSUE TITLE
Error loading this resource: 33c3 - Build your own NSA

### ISSUE THREAD

**Issue by pointhi** [voc/voctoweb#212]
Downloading the video works, but the embedded player returns an error message:

https://media.ccc.de/v/33c3-8034-build_your_own_nsa

**Comment by dedeibel** [comment]
Sorry, should have benn fixed by MaZderMind now. Please reload without caching.

**Comment by dedeibel** [comment]
https://github.com/voc/voctoweb/commit/693657ac0d63b4f191cdde4d91f145f1fd7e7415

**Comment by pointhi** [comment]
the issue was fixed, but now I get it again.
