### ISSUE TITLE
New logo for voctoweb

### ISSUE THREAD

**Issue by blinry** [voc/voctoweb#215]
Everyone I know is calling the platform "media.ccc.de". The header says "ccc-tv". The HTML title says "C3TV". I'd suggest changing all of these to "media.ccc.de".

**Comment by MaZderMind** [comment]
Yes, please. The times where we need to call ourselfs TV are long gone…

![TV](https://raw.githubusercontent.com/voc/voctoweb/c2c2c8d631b1a8d20ca45471660c34824a963254/app/assets/images/frontend/miro-banner.png)

**Comment by blinry** [comment]
Cool, how old is that that image? :)

If nobody has romantic feelings for the TV logo which is currently used as the favicon and in the header, I could also try to come up with something more expressive.

**Comment by MaZderMind** [comment]
I really don't know :) Removing the TV from the Favicon and Header seems logical, although I'd only change it if we can find something that is really better. Changing the TV to a Camera-Roll, for example, would not clarify anything. Finding a suitable Icon can be a challange and it might just not be possible.

Maybe it should be something very simple, like a playback-arrow: http://fontawesome.io/icon/play-circle/

**Comment by blinry** [comment]
Round 2:

![wip2comp](https://cloud.githubusercontent.com/assets/81277/23402634/c06d747a-fdac-11e6-93a1-28b6a38010f2.png)

**Comment by blinry** [comment]
Just give me an "okay", and I'll go ahead and create a PR which replaces the header logo and the favicons! :) Here's my preferred version:

![voctocat](https://pbs.twimg.com/media/C5xdojcWMAA0V1E.jpg:large)

**Comment by derpeter** [comment]
very nice. Which license do you choose for this?

**Comment by bjoern-r** [comment]
This should also be used for the default pause loop of voctomix

**Comment by blinry** [comment]
I'm glad that you like it! :) My default license would be CC BY-NC-SA 4.0, does that sound alright?

I'll clean up the SVG and put it online, so you can include it where ever you like! Pause loop is a great idea! In this project, it could also replace the [the bigplay button](https://github.com/voc/voctoweb/blob/431ed8efd86d6403fa8aa99c078438b2d383e8f6/vendor/assets/mediaelement/bigplay.svg).

**Comment by blinry** [comment]
The final logo is now available here: https://morr.cc/voctocat/ Had a lot of fun working on this! :)
