### ISSUE TITLE
Recommended/related videos

### ISSUE THREAD

**Issue by lukas2511** [voc/voctoweb#239]
It would be great to have recommended or related videos listed next or under the currently playing video.

On YouTube and other media platforms after playing a video (or if the current video is boring) many people look at the recommendation list and if there is something interesting it will be watched next.
I want people to keep watching talks instead of falling back to other media because it's easier to consume.

I've tried playing around with the API and building a different web-gui for voctoweb with a start-page of random videos and recommended talks (currently based on similarity of the title, which – at least in some cases – works surprisingly well, even without filtering stop-words etc.).

I've never written any code in Ruby so don't expect a pull-request from me any time soon.
This is just an idea for now. If somebody else wants to implement this that would be cool.

![mediacccde-tube](https://user-images.githubusercontent.com/85965/28501182-c5cbc61e-6fd6-11e7-942a-605e5afdaa06.png)

**Comment by manno** [comment]
For importing halfnarp data:

```
graph = {}
votes = JSON.parse(File.read('votes.json'))

votes.each { |vote|
  next if vote.count < 2
  vote.each { |event|
    print '.'
    node = if graph.key?(event)
             graph[event]
           else
             graph[event] = Hash.new { |h, v| h[v] = 0 }
           end

    (vote - [event]).each { |v|
      node[v] += 1
    }
  }
}
puts

def percentile(values, percentile)
  values_sorted = values.sort
  k = (percentile * (values_sorted.length - 1) + 1).floor - 1
  f = (percentile * (values_sorted.length - 1) + 1).modulo(1)

  values_sorted[k] + (f * (values_sorted[k + 1] - values_sorted[k]))
end

graph.each { |_id, edges|
  weights = edges.values
  next if weights.count < 2
  limit = percentile(weights, 0.95)
  edges.delete_if { |_k, v| v < limit.to_i }
}

def find_event(conference, id)
  conference.events.find_by('metadata @> ?', { remote_id: id.to_s }.to_json)
end

conference = Conference.find_by(acronym: '33c3')
graph.each { |id, edges|
  event = find_event(conference, id)
  next unless event
  sorted = Hash[edges.sort_by { |_, v| -v }]
  event.metadata[:related] = sorted.keys.map { |event_id|
    find_event(conference, event_id)
  }.compact.map(&:id)
  event.save
}
```

**Comment by manno** [comment]
With https://github.com/voc/voctoweb/commit/3d15b170b1cffcf80043c8913b16ff6f34683405 this is now live.
