### ISSUE TITLE
rss item flood

### ISSUE THREAD

**Issue by Matthias84** [voc/voctoweb#242]
Hi, from time to time I get hundreds till thousands of "new" video-items, but they all belong to shows that are already passed by. Maybe there is a bug, which emits old videos when internal process touch them?

**Comment by dedeibel** [comment]
Hi, could you please provide some video example entries?

**Comment by Matthias84** [comment]
Sure, for example when you pushed froscon2017 videos, also some old items of SHA2017 were marked as new (1000 new items in total).
![ttrss c3voc newold items](https://user-images.githubusercontent.com/217511/29496016-347517b0-85ca-11e7-8275-1b8e58534603.png)

I'm not sure if this is a bug of my TTRSS feedreader as well, or if the feed causes this problem in general :thinking:

**Comment by manno** [comment]
May be an issue with re-releases?

**Comment by saerdnaer** [comment]
Please reopen if issue still persists.
