### ISSUE TITLE
Custom header font

### ISSUE THREAD

**Issue by blinry** [voc/voctoweb#243]
Hi, designer of the [Voctocat](https://morr.cc/voctocat/) here! :) I think the "media.ccc.de" text in the header could use a prettier font with more character.

I made a few prototypes and gathered some feedback, and the one universally praised (for it's slight nerdiness and digital-ness) was [Russo One](https://fonts.google.com/specimen/Russo+One) by Jovanny Lemonad, released under the Open Font License.

Here's a mockup, where I also added a dash of color. What do you think? :)

![mockup](https://user-images.githubusercontent.com/81277/30240484-5035509e-9571-11e7-8409-336269b2b5b6.png)

**Comment by blinry** [comment]
And this could be a matching header for c3voc.de:

![c3voc](https://user-images.githubusercontent.com/81277/30240550-d20741e4-9572-11e7-9256-6a3ec9c97ec5.png)

**Comment by MaZderMind** [comment]
@blinry Hi! That looks nice, I like it.

**Comment by v0tti** [comment]
@blinry Good idea to improve the Font! But in the header it looks a bit heavy in relation to the Voctocat. Do you think this could be changed?

**Comment by blinry** [comment]
@v0tti Maybe you're right… here are two more variants with smaller text. I probably like the second-to-last one best, balance-wise:
![mockup2](https://user-images.githubusercontent.com/81277/30430492-b28519da-995b-11e7-9d96-ef8b544ea0fe.png)

**Comment by blinry** [comment]
Give me a thumbs-up, and I will go ahead and create a pull request with the second-to last font size! :)

**Comment by v0tti** [comment]
:thumbsup:

**Comment by blinry** [comment]
I'd love to create more headers for you, like the one above with the text "CCC Video Operation Center". Anything else that comes to mind?

**Comment by derpeter** [comment]
@blinry 
The Background / Banner on the front page is still 33c3 themed, this would be a great start to have there something nice thats event independent.
Besides that we have constant demand on theming the streaming website and intro for each event. The number of events that provide there own grafix is very low. If you are interested we should talk at the IRC.
