### ISSUE TITLE
Travis tests are broken for elastic search gauss scale

### ISSUE THREAD

**Issue by manno** [voc/voctoweb#248]
https://github.com/voc/voctoweb/blob/63317953452fcdddbcfc36bddb40ef4db2f5df5a/app/models/concerns/elasticsearch_event.rb#L58

https://travis-ci.org/voc/voctoweb/jobs/278498885

@MaZderMind Anyone know what the right value is?

**Comment by MaZderMind** [comment]
@manno interesting problem. It seems to be a recent change to not allow non-linear time-units (leap years etc.). See https://github.com/elastic/elasticsearch/issues/19619

Only seconds, minutes, hours and days are available in decay functions. 96w essentially means 2 years, so the closest approximation would probably be '730d'
