### ISSUE TITLE
RSS feed banner is old

### ISSUE THREAD

**Issue by manno** [voc/voctoweb#253]
Our [feeds](https://github.com/voc/voctoweb/blob/7532d73a703d720a53346bc30b00e146af04ba7c/app/controllers/frontend/feeds_controller.rb#L146) may be using an old banner: https://github.com/voc/voctoweb/blob/master/app/assets/images/frontend/miro-banner.png

**Comment by blinry** [comment]
I'll pick this one up and create a new one! :)

**Comment by blinry** [comment]
If I understand it correctly, this banner is only used in the podcast feeds, so it should be a square image, to be displayed nicely in podcatchers. How do you like this one?

![podcast](https://user-images.githubusercontent.com/81277/31360543-331c55d4-ad4f-11e7-9f5d-e52461e6b951.png)

**Comment by blinry** [comment]
I just went ahead and created a PR, see #257. I dropped the shadow behind the design, as I found it too oldschool.

Please merge or comment! :)
