### ISSUE TITLE
public API: add /public/conferences/:acronym

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctoweb#258]
During design of https://github.com/voc/streaming-website/issues/18 I came to the conclusion we probably should add /public/conferences/:acronym to the public API, simular as we did it for events, c.f. https://github.com/voc/voctoweb/blob/master/app/controllers/public/events_controller.rb#L14-L21

Instead of https://api.media.ccc.de/public/conferences/48 one could use https://api.media.ccc.de/public/conferences/oc without the need to lookup the internal voctoweb conference id beforehand. 

@manno Any objections?

**Comment by mkempe** [comment]
This is already implemented. Should be closed.
