### ISSUE TITLE
Edit button on public event page 

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctoweb#261]
As voctoweb admin I want a direct way to modify an events description to add additional metadata e.g. a link to a wiki page providing more information about a specific talk.

E.g. for https://media.ccc.de/v/gpn17-8619-hack_the_badge_-_preisverleihung 

Currently I have to login into the backend, click the event tab, copy the slug from the public event page 's URL into the search field, click the search button, click the one result to get to https://media.ccc.de/admin/events/3944/edit

A direct way e.g. an edit button or link on the bottom of the pubic event page would be helpful.

**Comment by manno** [comment]
Commited to HEAD
