### ISSUE TITLE
missing LICENSE.txt / what is the license for voctoweb

### ISSUE THREAD

**Issue by warrior1724** [voc/voctoweb#266]
HI 
I can't find LICENSE.txt or any licensing/copyright notice inside the code of voctoweb.
What is the license type / licensing model for voctoweb and for another project inside voc repositiories where LICENSE.txt is missig?

**Comment by manno** [comment]
I don't think we have any. Why do you want to know?

**Comment by warrior1724** [comment]
Dear Manno 
Thank you for prompt answer. 

I'm not lawyer but if you don't set license nobody will use your software LEGALLY. You and your team have all right (copyright) to work. 
Fork on github  or access to download does nothing with legal use.
 
Cleaning issue will license will help me to get your code, use it, modify it and maybe give feedback (patches/PR) and I will don't spend money for lawyer and potential lawsuit (nobody want to be sued)

**Comment by manno** [comment]
fixed in 382e415b95cf839a1369261c2bb8f78c285df8f9
