### ISSUE TITLE
Detail-View in Devenv broken because of related-fields

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctoweb#271]
@manno – any ideas what this relates to? I ran `./bin/update-data` and it fetched production-data.
![screenshot from 2017-11-14 23-31-49](https://user-images.githubusercontent.com/142237/32808800-99ebc7a2-c994-11e7-9de6-6c81fd58de70.png)

**Comment by MaZderMind** [comment]
It seems that the Dump contains the structured data formatted as a String (which is probably ok):
![screenshot from 2017-11-14 23-47-27](https://user-images.githubusercontent.com/142237/32809199-46c70dc8-c996-11e7-9aba-6b13fb0d92a7.png)

And the Field is also a jsonb-Field, but the import-thingy imports it as a json-string:
![screenshot from 2017-11-14 23-50-28](https://user-images.githubusercontent.com/142237/32809329-ba9f942c-c996-11e7-9604-0fdbca2b6e67.png)

Which is then loaded as a String into the application.

**Comment by manno** [comment]
Ah, so that's where the strings come from.  Maybe we can fix this in the dump/restore rake tasks.

I just ran `Event.all.each { |e| e.update_column(:metadata, JSON.parse(e.metadata)) }` previously.

**Comment by MaZderMind** [comment]
Sounds like a reasonable option for imporing demo-data. This would probably also affect the existing jsonb fields.

**Comment by MaZderMind** [comment]
That works for Event.metadata and Conference.streaming but Conference.metadata is seriously broken and I can't imagine this working in the prod env ;)

![bildschirmfoto 2017-11-16 um 15 14 12](https://user-images.githubusercontent.com/142237/32895922-e8ee8da0-cae1-11e7-93b5-9ad3d495ff7a.png)

**Comment by manno** [comment]
Uh, yeah don't run update-data on production.

**Comment by MaZderMind** [comment]
@manno The problem originates from faulty data in the production database:
![screenshot from 2017-11-19 13-29-15](https://user-images.githubusercontent.com/142237/32990664-b76231ee-cd2d-11e7-9423-f779355cd606.png)

The root cause is probably the textfield that once exposed the metadata for editing in the admin-ui.

**Comment by manno** [comment]
Ok, I fixed those.
