### ISSUE TITLE
Public API: Confernces don't contain a date

### ISSUE THREAD

**Issue by NiciDieNase** [voc/voctoweb#275]
Would be very useful for chronological sorting, etc.

**Comment by saerdnaer** [comment]
Workaround: Use voctoweb internal id ;-)

**Comment by cweiske** [comment]
We'd like to sort conferences by date (newest first), and this issue here is hindering us.

**Comment by saerdnaer** [comment]
Here an example for the 34C3
```json
{
"acronym": "34c3",
"aspect_ratio": "16:9",
"updated_at": "2018-01-10T16:25:09.726+01:00",
"title": "34C3: TUWAT",
"schedule_url": "",
"slug": "congress/2017",
"webgen_location": "congress/2017",
"logo_url": "https://static.media.ccc.de/media/congress/2017/media-logo.png",
"images_url": "https://static.media.ccc.de/media/congress/2017",
"recordings_url": "http://cdn.media.ccc.de/congress/2017",
"url": "https://api.media.ccc.de/public/conferences/132"
},
```
We currently only have updated_at, and as a workaround extract the id from url and thereby sort by creation time. So which date would you like us to add? Startdate of the conference, Enddate of the conference?

**Comment by manno** [comment]
The event has several dates: https://github.com/voc/voctoweb/blob/master/app/views/public/shared/_event.json.jbuilder#L1 and belongs to a 'conference'.

Problem is 'conferences' are not really conferences. We debated renaming this countless times. A conference is really more like a channel.
What would be the 'date' of https://media.ccc.de/c/oc ?

**Comment by cweiske** [comment]
For me the use case of a date in the event list would be to be able to sort the list to have newest first, a chronological order.

If I understand @manno correct, then there are two types of "conferences": Conferences that have a defined start and end date, and continuous "series" that now and then get a new event.

For my use case, the date of the recording of the latest event in a conference would perfectly fine:

- It allows sorting by chronological order for "normal" conferences
- It pushes continuous series onto the top whenever a new event is added to them.

**Comment by manno** [comment]
I think we have something like this: https://github.com/voc/voctoweb/blob/master/app/models/event.rb#L36
I guess it's missing from the JSON?

**Comment by cweiske** [comment]
Yes, that's missing from JSON.

**Comment by manno** [comment]
`event_last_released_at` was added in commit 2e640a6

**Comment by cweiske** [comment]
@manno: Something is strange. "Linuxtag 2006" is shown as having had updates in 2019, which I can't really believe: https://api.media.ccc.de/public/conferences/154
Do you know which update this was?

This makes ordering by the `event_last_released_at` useless for me.
