### ISSUE TITLE
remove tabs from audio files

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctoweb#276]
Das initale Design der Event Seite, sah eigentlich vor das es pro Sprache ein Audio-only Release gibt. Ist aber seit dem 33C3 nicht mehr der Fall – Dann könnte man die Sache mit Tabs bei den Audio Dateien auch gleich sein lassen...

@MaZderMind, @jjeising Was denkt ihr dazu?

Vorher:
<img width="703" alt="vorher" src="https://user-images.githubusercontent.com/40266/33800881-6829e586-dd4a-11e7-98a3-0af3a8c82998.png">

Nachher:
<img width="706" alt="nachher" src="https://user-images.githubusercontent.com/40266/33800900-d1918470-dd4a-11e7-96a0-9b6d2d8c43e9.png">

**Comment by MaZderMind** [comment]
Da das weder für den 30C3, 31C3, 32C3 noch für den 33C3 gemacht wurde: go von mir
