### ISSUE TITLE
Fullscreen gets clipped on non-standard screen ratios

### ISSUE THREAD

**Issue by lroellin** [voc/voctoweb#277]
I own a 21:9 screen and when I watch fullscreen videos, e.g. https://media.ccc.de/v/33c3-8029-the_ultimate_game_boy_talk, the screen gets clipped at **bottom**. I've included a screenshot (may take some time to load). This is taken at 3:38 into the video.

![fullscreen_21_9](https://user-images.githubusercontent.com/3150983/33808820-d7cf2098-ddec-11e7-8cdb-03fa2f501d3b.png)

I'm not sure it matters, but I'm using Chrome 62.0.3202.94 on Windows 10 Fall Anniversary Edition 1709 (Build 16299.94).

**Comment by saerdnaer** [comment]
This should be fixed, once #280 is merged

**Comment by saerdnaer** [comment]
@lroellin Is this still an issue, now after the player upgrade?

**Comment by lroellin** [comment]
I'll check tomorrow!

**Comment by lroellin** [comment]
I'm only on my Mac now, but seems to work there on this screen. I'll close it, thank you for your help!
