### ISSUE TITLE
RSS Feeds: create a dedicated master-mp4 feed

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctoweb#283]
The current mp4 rss feed (e.g. https://media.ccc.de/c/33c3/podcast/mp4.xml ) selects the first video recoding with a html5 flag. For single language conferences this is probably the master-mp4 but for multilanguage conferences like the xC3 this one of the single language files. The mp4 sd feed and webm feeds contains files with all language tracks.

But when people want to download all recordings in one format, they probably also want also all language tracks and not only the original one.

* [ ] add a list of used languages at the conference metadata field

Options:
 - a) change the existing feed (https://media.ccc.de/c/33c3/podcast/mp4.xml) to output the master MP4 files (sort by language field length + high_quality flag)
 - b) add an additional feed https://media.ccc.de/c/33c3/podcast/mp4-master.xml, which always links to the master mp4 file 
 - c) optional: add new feeds like  https://media.ccc.de/c/33c3/podcast/mp4-single-lang.xml?lang=eng with default https://media.ccc.de/c/33c3/podcast/mp4-single-lang.xml?lang=orig – compare #195 

When changing the existing feed we might get a noticeable amount of users which don't find the button to change the audio track from their OS system language to the original language....

**Comment by saerdnaer** [comment]
https://github.com/voc/voctoweb/commit/f63de873e8f2dd314de4d35e2ef008201733b152 added an mp4-master podcast feed, e.g. for mass download usage as described on https://events.ccc.de/congress/2017/wiki/index.php/Static:Streams

**Comment by meise** [comment]
Kann dit zu?

**Comment by saerdnaer** [comment]
Yup!
