### ISSUE TITLE
Changing an event doesn't expire the conference cache on the front page

### ISSUE THREAD

**Issue by TobiX** [voc/voctoweb#285]
If something changes on an event, but not on the conference, the nested cache on the front page isn't updated. If I understand this correctly (see http://guides.rubyonrails.org/caching_with_rails.html#russian-doll-caching), https://github.com/voc/voctoweb/blob/master/app/models/event.rb#L8  is missing a `touch: true` to make this work correctly.

**Comment by TobiX** [comment]
I just noticed https://github.com/voc/voctoweb/blob/master/app/models/event.rb#L46 - not enough?

**Comment by manno** [comment]
There might be a situation where the models aren't touched. However it's more likely you're running into the nginx cache in front of the app server. The good news is, just waiting normally fixes it.
Is it ok now?

**Comment by TobiX** [comment]
Still broken:

![grafik](https://user-images.githubusercontent.com/78534/34201648-7cdb6a80-e575-11e7-8962-a4bc69697c59.png)

**Comment by manno** [comment]
I had a problem with deleted events. Maybe this is related. Conference should be touched after destroy?
Someone wants to test and do a PR?
