### ISSUE TITLE
Add transcripts to be indexed by full text search

### ISSUE THREAD

**Issue by 9er** [voc/voctoweb#289]
Hi there, I've got a feature request that I'm thinking about for a while now.

Sometimes I find videos on media.ccc.de (by chance) about a topic I was looking into months ago, but didn't find the video. The talks often have titles that are cryptic, puns, or in another language, which makes them hard to find. Sometimes I remember a few key sentences or punch lines from a talk, but can't find it by them.

Here's my proposal:
I know that there are transcripts for a few of the talks. I actually helped transcribing a few talks some years ago. If the transcript gehts loaded with the video in the web-player, e.g. in a pane that is collapsed by default, search engines would index it and one would be able to find the recordings of the talks much easier and more casually.

**Comment by Happy86** [comment]
Subtitles can be synced from https://mirror.selfnet.de/c3subtitles/congress/

**Comment by 9er** [comment]
Since the topic was changed, I'd like to emphasize that it's important that not only the websites own search index contains the transcripts, but also that third party search engines like Google can index them.

**Comment by dpunkturban** [comment]
+1 would be a nice feature

what is the current state? do you need any help?

**Comment by manno** [comment]
I don't think we have the transcripts in our database at all. They are in the CDN, but we would have to upload them to the app server and store them in some database?

**Comment by saerdnaer** [comment]
We will have the srt files in the database once #382 is implemented.
To implement this issue we need a method which downloads the srt file from it's source, prepare that file's content, removes the old content from a previous version of the subtitles from the search index, add's the new content to the search index.

**Comment by saerdnaer** [comment]
As of now vocotoweb knows when there is a transcript. Maybe we should add an state column to the recordings table, and add a worker which downloads the transcripts of all new SRT-recordings to be added to the elasticsearch index.

**Comment by saerdnaer** [comment]
Was implemented
