### ISSUE TITLE
API change: related Events saved in Metadata changes from JSONArray to JSONObject

### ISSUE THREAD

**Issue by stefanmedack** [voc/voctoweb#297]
This API change is not very recent, but I always forgot to add an issue for it. For some reason the field of related events saved in the Metadata of an Event has been changed from JSONArray to a JSONObject in the API. This leads to problems in parsing the Metadata for example in https://github.com/johnjohndoe/c3media-base by @johnjohndoe or in my project that uses this library https://github.com/stefanmedack/cccTV

Is it possible to revert this change at least for the API? I would also argue that it does not make sense to save a list of related events as a key/value pair, since it is a list and can now hardly be parsed or iterated (at least in Java/Kotlin, but most likely in other languages as well).

**Comment by saerdnaer** [comment]
Can you provide before/after example snippets?

**Comment by manno** [comment]
@stefanmedack  or just the API URL where this happens

**Comment by stefanmedack** [comment]
Okay, in this case that is unfortunate for us. But again: wouldn't it make sense to still use a list of objects. So I would suggest to change the structure to 

```
{
  "related": [
     {
         "eventId" : "2983": 
         "whateverThisValueIsFor": 2
     },
     {
         "eventId" : "3466": 
         "whateverThisValueIsFor": 2
     }
  ],
  "remote_id": "7726"
}
```

**Comment by manno** [comment]
I don't think it would make sense to change that for voctoweb internally?
By using a hash data structure (id: weight) voctoweb gets unique keys and merging based on keys for free.

I would consider a PR which change this externally for API clients in the view at `app/views/public/shared/_event.json.jbuilder`.

**Comment by johnjohndoe** [comment]
@manno Do I correctly understand that you would be fine with changing the public API for `public/events/` to output the following:

``` json
...
{
  "related": [
     {
         "event_id" : "2983",
         "weight": 2
     },
     {
         "event_id" : "3466",
         "weight": 2
     }
  ],
  "remote_id": "7726"
}

**Comment by saerdnaer** [comment]
Idea for the future: We should thinking about solving such issues with a new GraphQL API.

**Comment by johnjohndoe** [comment]
✅ Fixed in the _c3media-base_ client library [here](https://github.com/johnjohndoe/c3media-base/commit/1e4a62fb42145d22bf11f2d11646ea0fc0f616fd). /cc @stefanmedack
