### ISSUE TITLE
Add Playlist to the WebUI

### ISSUE THREAD

**Issue by binek** [voc/voctoweb#298]
I'd love to have the possibility to save a List of Talks i want to watch. Could be a Playlist or Bookmark List or something

**Comment by saerdnaer** [comment]
Where should this list be stored? In your own browser via a cookie?

**Comment by MaZderMind** [comment]
Recent browsers have a really strong LocaleStorage [1] API, I'd not show this feature if a browser would not support LocaleStorage and build it based on this API.

[1] https://developer.mozilla.org/de/docs/Web/API/Storage

**Comment by derpeter** [comment]
There where already discussions for this topic. There are some basics to keep in mind:
* We don't want to have private data
* We don't want to track our users
* We don't want to have user input except for the search

Local storage would be an option but that would limit the functionality to one device / browser.
Another solution would be a community hosted service which could also interact with halfnarp and the android / ios apps and plugins.

A simply api which e.g. uses a random hash as identifier could provide this functionality in an platform independent way and would be totaly opt-in.

Another way would be to encode this list in the URL like halfnarp does this. This would not be that convenience but would still be more flexible than local storage

**Comment by manno** [comment]
Yeah, any PR is welcome at this point...

**Comment by manno** [comment]
Regarding the UI #118

**Comment by saerdnaer** [comment]
@manno Hast du das Feature schon irgendwo beschrieben? Bzw. Kannst du nen Gif davon machen o.ä...?
