### ISSUE TITLE
OEmbed broken in diaspora

### ISSUE THREAD

**Issue by svbergerem** [voc/voctoweb#300]
The preview looks good but when starting the video the player is not usable.

![preview](https://user-images.githubusercontent.com/3798614/34692994-ff25343c-f4b9-11e7-83c7-1e3748eb1e3b.png)

![video playback](https://user-images.githubusercontent.com/3798614/34693107-6166b954-f4ba-11e7-9264-97fec65b6828.png)

The height of the element `.mejs.fill-container` is explicitly set to 17px.

![fill-container height](https://user-images.githubusercontent.com/3798614/34693079-4d021206-f4ba-11e7-8973-bbc46c6bd8ba.png)

Disabling this style fixes the issue.

**Comment by saerdnaer** [comment]
@svbergerem Are you using Firefox?

**Comment by lostinlight** [comment]
I can confirm I've had same behaviour on Firefox and Chromium.

**Comment by svbergerem** [comment]
@saerdnaer Yes, Firefox 57 on Arch Linux.

**Comment by saerdnaer** [comment]
@lostinlight Was still the case when you wrote this comment, or did you refer to a previous experience? Can you provide an URL where I can debug the problem?

**Comment by lostinlight** [comment]
@saerdnaer It was the case when I wrote the comment (still is), Firefox 55 on Linux. Don't have Chromium on the current machine, can check again later, I think it was version 63.0.3239.108.

To fix the player, I have to manually change `.mejs.fill-container` height to a larger number (300px) and disable `overflow: hidden`. 

This [URL](https://pod.geraspora.de/posts/e94a4d10d36801351c59101b0e8ace24), for example.

**Comment by saerdnaer** [comment]
Just for clarification:
PR #290 upgraded the mediaelement player from 2.23.4 to 4.2.7, which introduced a new config attribue 'stretching' [[1]](https://github.com/mediaelement/mediaelement/blob/master/docs/usage.md#use-stretching-modes), which I initially set to _responsive_. 

With https://github.com/voc/voctoweb/commit/60d2aab0d8c7d567205450242cbe635dba5f21c5 I changed that to _responsive_ for the default player page, and _fill_ for the oembed version – which fixed the embed problem for most browsers, besides firefox – as we now discovered.

**Comment by saerdnaer** [comment]
Current suspicion: There is a bug in this code block: https://github.com/voc/voctoweb/blob/a3e5ce0076af062432ef53c24227c39649b65ab1/vendor/assets/javascripts/mediaelement-and-player.js#L4497-L4520

Interessing (closed) upstream issue: https://github.com/mediaelement/mediaelement/issues/2200

**Comment by MaZderMind** [comment]
That code is so incredibly convoluted /o\

**Comment by MaZderMind** [comment]
@blinry just fyi: this would be one of many reasons why we really want to get rid of mediaelement.js
