### ISSUE TITLE
apple TV app does not get content using ipV6, ipv4 seems fine

### ISSUE THREAD

**Issue by gramels** [voc/voctoweb#301]
also cant ping6 media.ccc.de

```
$ host media.ccc.de
media.ccc.de has address 195.54.164.138
media.ccc.de has IPv6 address 2001:67c:20a0:b::138
$ ping6 2001:67c:20a0:b::138
PING6(56=40+8+8 bytes)  --> 2001:67c:20a0:b::138
^C
--- 2001:67c:20a0:b::138 ping6 statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss
$ ping media.ccc.de
PING media.ccc.de (195.54.164.138): 56 data bytes
64 bytes from 195.54.164.138: icmp_seq=0 ttl=55 time=15.185 ms
64 bytes from 195.54.164.138: icmp_seq=1 ttl=55 time=15.296 ms
^C
--- media.ccc.de ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 15.185/15.241/15.296/0.055 ms
$ ping6 media.ccc.de
PING6(56=40+8+8 bytes) --> 2001:67c:20a0:b::138
^C
--- media.ccc.de ping6 statistics ---
4 packets transmitted, 0 packets received, 100.0% packet loss
```

**Comment by MaZderMind** [comment]
Pings fine for me (from multiple networks)
![screenshot from 2018-01-14 11-38-08](https://user-images.githubusercontent.com/142237/34915117-3eebb4be-f920-11e7-82c3-e819a0134794.png)
![screenshot from 2018-01-14 11-44-03](https://user-images.githubusercontent.com/142237/34915118-3f03f7c2-f920-11e7-9c54-7879511ac0ee.png)

Furthermore this is the Issue-Tracker for the Software and this obviously is not a Software-Issue (at least not of he Rails-App), better use the Mailing-List media@koeln.ccc.de for operational Questions.
