### ISSUE TITLE
Add a way to stop recommended movement

### ISSUE THREAD

**Issue by licaon-kter** [voc/voctoweb#303]
When having the window width small enough (eg. have 2 windows tiled side by side, each has screen width/2), the recommended videos carousel appears (albeit partially) on screen and it never stops moving making video watching a pain.

![pic](https://i.imgur.com/lVuzCoQ.jpg)

**Comment by saerdnaer** [comment]
@manno What do you think about moving the related section down, after the downloads section?

**Comment by licaon-kter** [comment]
Whatever helps.

Can the page detect if the video is playing and stop the movement if it is?

**Comment by manno** [comment]
Does anyone have time to do a PR? I guess we just need to configure the slider?
