### ISSUE TITLE
Expose IDs in API

### ISSUE THREAD

**Issue by rixx** [voc/voctoweb#314]
I'd appreciate it if talks and conferences had their ID exposed as a field in the API. Currently I'm splitting the `url` field on `'/'` and take the last part, but avoiding this extra step would be nice.

**Comment by manno** [comment]
Hi, what's your use-case?
You can get the conferences by `acronym` and the events by `guid` (https://github.com/voc/voctoweb/blob/master/app/controllers/public/events_controller.rb#L18). I'd rather not expose database IDs in the API.

**Comment by rixx** [comment]
Database IDs are already exposed via the `url` field, only not directly. Is there a reason not to expose them further?

I used the `acronym` and `guid` paths previously (very useful btw, thanks!), but the related events are only referenced by ID, so any client application using those will have to know the voctoweb event IDs.

**Comment by rixx** [comment]
If you want to treat event guids as the canonical address and name though, I can also submit a PR to add those to the related event outputs instead of the event ids, I just wasn't sure if I'd break any existing consumers/APIs with that change.
