### ISSUE TITLE
Private API: Setting conference title and logo

### ISSUE THREAD

**Issue by lukas2511** [voc/voctoweb#319]
I tried creating a conference using the private API and I was unable to set a conference title or logo.
I'm not sure if I'm hodling it wrong or if those parameters are just not accepted, a clarification for how to do this or a fix would be nice :)

**Comment by manno** [comment]
https://github.com/voc/voctoweb/blob/ac514489495339b0d5f84fbfce3e6dc64fa5698e/app/controllers/api/conferences_controller.rb#L65

`logo` and `title` are missing from the list. Apparently catching unpermitted parameters is a application wide config (https://medium.com/@tbrisker/strong-parameters-in-rails-down-the-rabbit-hole-2426d331625). Not sure if I want to deal with the outcome.

**Comment by manno** [comment]
Fi
