### ISSUE TITLE
Include/display magnet link

### ISSUE THREAD

**Issue by NicApicella** [voc/voctoweb#32]
Feature-request:

Instead of/in addition to linking to .torrent-files in the download section, include (or rather display—I'm told they exist already interally) magnet links.

**Comment by manno** [comment]
Sure, pull requests are welcome.

**Comment by MaZderMind** [comment]
Depends on a possible shift to mirrorbit, possibly related to bitlove.

**Comment by saerdnaer** [comment]
Wo do not have torrent files anymore.
