### ISSUE TITLE
Javascript error when navigating to a video page

### ISSUE THREAD

**Issue by blinry** [voc/voctoweb#321]
When loading the main page, and then clicking on a video, Voctoweb throws an `Uncaught ReferenceError: MirrorbrainFix is not defined`, and the Mediaelement player does not load. When reloading the video page, it works.

This bug was introduced in 37d1146d416b86fbd7f62ca737a8221db70b7542, when inclusion of the `mirrorbrain-fix` was moved from *application.js* to *mediaelement-player.js*. I suspect it has something todo with the *turbolinks* gem, which does not load the Javascript in `<head>` properly. The easiest fix is probably to move the inclusion back to *application.js*?

**Comment by manno** [comment]
That could work, did you try? I wonder if the players load at all if this fails: https://github.com/voc/voctoweb/blob/master/app/views/frontend/events/show.html.haml#L26

**Comment by blinry** [comment]
Moving back `mirrorbrain-fix` (only) to *application.js* does not help, then indeed the `mediaelementplayer` function is not defined when navigating to the video. What was the problem solved by 37d1146d416b86fbd7f62ca737a8221db70b7542?

**Comment by manno** [comment]
Errors introduced by PR #273 

I'd try to disable turbolinks instead of putting both players in the same `applications.js`?

**Comment by saerdnaer** [comment]
@blinry Can you check if this issue is still valid?

**Comment by blinry** [comment]
Nope, doesn't seem to be the case. :) Closing.
