### ISSUE TITLE
Implement public GraphQL API 

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctoweb#329]
TODOs
* [x] implement and deploy basic schema (PR https://github.com/voc/voctoweb/pull/340)
* [x] extend schema with more attributes (PR https://github.com/voc/voctoweb/pull/411)
* [ ] optimize resolvers with https://github.com/Shopify/graphql-batch 

with http://graphql-ruby.org
Related discussions: #316 #297

**Comment by manno** [comment]
So GraphQL solves this by adding a `deprecated` flag to fields and counting field usage? So we'd still have to keep the old code around until usage drops?

It would be a nice addition to the existing endpoints, but I don't see it as a replacement. After reading https://blog.runscope.com/posts/you-might-not-need-graphql I'm a little bit afraid of opening up the  database to queries. Mostly performance wise.

Can you explain what would be the advantage of adding a query language to our existing APIs?

**Comment by saerdnaer** [comment]
Yes, it is not a replacement for the REST API, but a nice addition to solve our API versioning problem: The client can gradually decide with attribute it needs, and you can experiment mire easily – c.f. "How to store the slides timestamps" discussion around last C3. 
It migh

BTW: GraphQL actually it not a query language as spec misses selection. Neither or less, if it lets you sleep better at night, I can keep the possible recursions as low as possible... :-)

**Comment by manno** [comment]
Maybe `asset` instead of `recording`? And if we could rename `Conference` to `Channel`, that would be great...

**Comment by saerdnaer** [comment]
First draft:
<img width="969" alt="image" src="https://user-images.githubusercontent.com/40266/46570651-aca35580-c967-11e8-9ee1-dfb2a84d7a7c.png">

**Comment by saerdnaer** [comment]
Lightning-Talk about this Issue at this weekend's geekend: https://media.ccc.de/v/geekend2018-5-graphql
