### ISSUE TITLE
Docker: update-data kills elasticsearch container

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctoweb#341]
When setting up the docker version of voctoweb as described in https://github.com/voc/voctoweb#set-up-development-environment, during the last step auf the update-data script, the elastic search container is killed with exit code 137. The update script fails with `== Command ["bin/rails runner \"Event.__elasticsearch__.create_index! force: true; Event.import\""] failed ==`

@blinry Any idea what's causing this issue?

**Comment by blinry** [comment]
Has this issue been fixed during the recent Docker setup overhaul? :)

**Comment by albjeremias** [comment]
true story! happened to me too! :cry:

**Comment by albjeremias** [comment]
you can close.. this was because i was to excited to try this out.. and opened the browser before the updates were finished :blush:
