### ISSUE TITLE
Change publishing_date from date to datetime

### ISSUE THREAD

**Issue by bitrage** [voc/voctoweb#343]
The sorting via "date" just takes the date of the original talk into account. Maybe only the date and not the time.

If you would like to follow a whole event this is not really useful. When you sort by date and frequently check for new videos, you might not catch videos that are inserted somewhere in the middle because the publishing process got delayed.

A sorting by publishing date (or simple item/row id) would remedy that issue and enable you to remember the last published video to check whether there are new entries since the last visit.

**Comment by saerdnaer** [comment]
https://media.ccc.de/recent should be sorted by publishing date. Does that work for you?

**Comment by bitrage** [comment]
I don't think so. Currently the "Opening Event" is the first video in the list, but it is not the most recent published video. At the moment that would be >>"The" Social Credit System<<

**Comment by saerdnaer** [comment]
An `Event` has actually four different dates: `created_at`, `updated_at`, `date` (the date the lecture took place) and `release_date`, whereby the first three are of type `timestamp without time zone` and the  `release_date` is of type `date`, which has no time... We will discuss if we should change the type of `release_date`, but there is not really an easy fix as we might create the events in future before the talks has taken place.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/40266/50489137-53970b00-0a06-11e9-8102-d2ae0d27ea6d.png">

**Comment by bitrage** [comment]
I don't know what counts as "updated_at", but that sounds kind of promising? Or is there usually too much updating after publishing to be meaningful?

**Comment by manno** [comment]
I think `created_at` is the safest choice if we want to consider time.

**Comment by manno** [comment]
35c3 is over and most videos should be released. Do we still want to change the order?

* Clicking on the date column sorts by `date, release_date` (https://github.com/voc/voctoweb/blob/master/app/controllers/frontend/conferences_controller.rb#L6)
* The recent page already sorts by `created_at (`https://github.com/voc/voctoweb/blob/master/app/models/concerns/recent.rb#L7)

I think recent is useful while the event is running. The conference view sorted by the date column, I don't know.

**Comment by saerdnaer** [comment]
Which is now problematic as we use the relive feature in media, and the events aka lectures get created before the actual release of the master file.

**Comment by saerdnaer** [comment]
fixed with https://github.com/voc/voctoweb/commit/72a67dfc70a0269ee1101e03abbea0a19f14b545
