### ISSUE TITLE
Switch to DASH player

### ISSUE THREAD

**Issue by manno** [voc/voctoweb#351]
The player used for relive [clappr](https://github.com/clappr/clappr) does support DASH via https://github.com/clappr/dash-shaka-playback

mediaelement.js also supports DASH.

Can we switch the default player from webm/mp4 pseudo streaming to DASH?

Does the player support:
* multiple audio tracks (switching)
* subtitles
* adaptive quality
* ...?

**Comment by saerdnaer** [comment]
Duplicate of #264 ?

**Comment by manno** [comment]
Hm, #290 doesn't mention DASH and is more generic. Let's close it?

**Comment by saerdnaer** [comment]
media.ccc.de now supports DASH when you append `?player=clappr` to the url of a lecture/event page and a recording of type dash is added to the event, e.g. https://media.ccc.de/v/c4.openchaos.2019.09.media?player=clappr
