### ISSUE TITLE
35C3 Infrastructure Review not uploaded correctly

### ISSUE THREAD

**Issue by slisystem** [voc/voctoweb#353]
Hey everyone,

the "35C3 Infrastructure Review" (https://media.ccc.de/v/35c3-9576-35c3_infrastructure_review) upload seemed not to have worked correctly.

**Comment by davidak** [comment]
I got a response:

> Das ist nur ein Bug im Frontend. Ein Fix wird zeitnah ausgerollt. Bis dahin einfach hier entlang: https://streaming.media.ccc.de/35c3/relive/9576 … ^fl

https://twitter.com/c3voc/status/1079509199573405697

**Comment by florolf** [comment]
Fixed, thanks for reporting!
