### ISSUE TITLE
Videos player on Panasonic TVs

### ISSUE THREAD

**Issue by Djfe** [voc/voctoweb#354]
Hi everyone,
I just had the idea to watch some videos of ccc talks on my new Panasonic TV (TX-55FZW835) from 2018
Sadly the playback fails, it just displays this error message:
![image01](https://user-images.githubusercontent.com/5685512/50564794-6708e580-0d28-11e9-804c-d6ca4ad3a1d3.jpg)

This is what the included browsers supports (according to the html5test I just ran):
http://html5test.com/s/8853c1421e34ccc8.html

I noticed, that media.ccc.de seems to be using mediaelement.js so I visited their website:
the videos on the front page play just fine on the tv (mp4, hls, mpeg-dash, youtube)

So it might just be a configuration issue
Or the browser chokes on the mp4 files for some reason.

I would be glad, if someone could take a look :)

I'm ready to help with the debugging

**Comment by TheAssassin** [comment]
Send in your TV for debugging, and you will receive it again in 2-3 congresses, but then it'll work.

</sarcasm>

Did you try to play the WEBM video directly (as in, click on the right "download" button)? Please do the same for MP4, and see which formats can be played back by your TV (they should be played right in the browser).

**Comment by TheAssassin** [comment]
So, forget about the WEBM files. According to the page you linked, VP8 is not supported. The WEBM files available from media.ccc.de are encoded in VP8, though. No chance to get that to run on your TV. Your OS and browser are quite old by the way.

H.264 and AAC are apparently supported, so the question is whether your TV even tries those. If yes, the question is whether it has issues with the container format etc. Really hard to inspect, as those kinds of TVs are black boxes anyway, and without hands on even harder.

**Comment by Djfe** [comment]
Yeah the user agent is fairly interesting :D 
I can assure you that it isn't accurate though
My bet is that the devs never bothered to update the user agent in all those years.
While the TV might use Firefox 34 in the background, that version isn't from 2010 (it's younger).
And again the TV and it's software is from 2018. It could also be that Panasonic just uses a user agent that looks like Firefox (like Edge uses a chrome user agent to prevent compatibility issues with stupid websites)

If it's a bug in the browser, then I can open a bug report on panasonics end, if I know what the actual issue is.

Clicking on download opens the video in a new page, but I get the same error.
While this might be due to the TV's software, I can also imagine that it might be due to some headers/mime types that the server send's to the tv (that the tv doesn't understand so it doesn't even try to decode the mp4)

I bet that it isn't easy to debug this.
But what I just noticed:
Why is the mime type (Content-Type) in the server's reply
`text/html; charset=utf-8`
when it returns the mp4 file? Shouldn't it be:
`video/mp4`
Fixing that might already convince my tv to play the file :)

**Comment by Djfe** [comment]
also the other media files (track selection) seem to be loaded in using xhr and have the mime type
`application/json; charset=utf-8`
While this might be no problem, I thought, I would mention it as well.

**Comment by Djfe** [comment]
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Configuring_server_MIME_types

> By default, many web servers are configured to report a MIME type of text/plain or application/octet-stream for unknown content types. As new content types are invented or added to web servers, web administrators may fail to add the new MIME types to their web server's configuration. This is a major source of problems for users of Gecko-based browsers, which respect the MIME types as reported by web servers and web applications.

**Comment by Djfe** [comment]
When I select other media tracks
(or switch back to english/the first video afterwards)
then their mime type is video/mp4.
But the first time it's retrieved from the server, it's html for some reason

Also:
why do the video urls look like this?
https://mirror.netcologne.de/CCC//congress/2018/h264-hd/35c3-9999-eng-The_Enemy.mp4
instead of
https://mirror.netcologne.de/CCC/congress/2018/h264-hd/35c3-9999-eng-The_Enemy.mp4
(What are the two slashes for)

**Comment by TheAssassin** [comment]
> (What are the two slashes for)

Extra slashes don't hurt normally. Probably a string concatenation problem somewhere.

```sh
> http --headers https://mirror.netcologne.de/CCC//congress/2018/h264-hd/35c3-9999-eng-The_Enemy.mp4
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 556677091
Content-Type: video/mp4
Date: Thu, 03 Jan 2019 14:52:09 GMT
ETag: "5c2d2323-212e37e3"
Last-Modified: Wed, 02 Jan 2019 20:46:27 GMT
Server: nginx/1.15.6
```

MIME type looks good to me. Can you give an example URL where you received a wrong MIME type?

**Comment by saerdnaer** [comment]
@TheAssassin Könntest du dich bitte etwas zurückhalten wenn du das eigentliche Problem nicht verstanden hast?

@Djfe The screenshot shows the Non-JavaScript HTML5 video tag. 
The tv probably can not handle multiple source tags. You can copy the HTML source of an event page to your own web server, add an `<base href=“https://media.ccc.de/“ />` to the header and experiment with removing the different source tags inside the video tag.

**Comment by Djfe** [comment]
it's only happening for the first video being loaded:
`> http --headers https://cdn.media.ccc.de/congress/2018/h264-hd/35c3-9999-eng-The_Enemy.mp4
HTTP/1.1 302 Found
Access-Control-Allow-Origin: *
Cache-Control: private, no-cache
Connection: keep-alive
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Fri, 04 Jan 2019 14:02:36 GMT
Link: <https://mirror.netcologne.de/CCC/congress/2018/h264-hd/35c3-9999-eng-The_Enemy.mp4>; rel=duplicate; pri=1; geo=de
Link: <https://ftp.halifax.rwth-aachen.de/ccc/congress/2018/h264-hd/35c3-9999-eng-The_Enemy.mp4>; rel=duplicate; pri=2; geo=de
Link: <https://mirror-1.server.selfnet.de/CCC/congress/2018/h264-hd/35c3-9999-eng-The_Enemy.mp4>; rel=duplicate; pri=3; geo=de
Link: <https://ftp.fau.de/cdn.media.ccc.de/congress/2018/h264-hd/35c3-9999-eng-The_Enemy.mp4>; rel=duplicate; pri=4; geo=de
Location: https://berlin-ak.ftp.media.ccc.de/congress/2018/h264-hd/35c3-9999-eng-The_Enemy.mp4
Server: nginx/1.10.3 (Ubuntu)`

![firefox_2019-01-04_15-04-12](https://user-images.githubusercontent.com/5685512/50691787-08967c80-1032-11e9-852c-365148457d12.png)

**Comment by Djfe** [comment]
ok I was about to test it on the tv but playback is working now
did you change something?
I didn't (except that I restarted the router(lan switch) that the tv is connected to)

I still did a few tests.
several source tracks don't seem to cause any issues for the tv
and I removed all source tracks from the html and then tested them one by one

the only one that doesn't work is the 4th which is the only stream that is vp8 only (webm hd)
webm sd also has vp9 video in it and therefore it seems to work

The only annoying thing is how the tv chooses the source track to play
I can't choose the language
sometimes it chooses the german dub (would be fine, I'm from germany, but I would prefer the original language), once it chose the french dub
playing the download still doesn't work (the mp4 directly)
I'm not sure how the tv chooses the track, it doesn't honor the order in the video tag

another question I had regarding the tracks:
is it a mediaelements config, that the custom player gui isn't shown on the panasonic tv? (or is it a workaround since that gui doesn't work?)
Right now I have no button which I could use to try whether switching tracks/media files would even work
The buttons just aren't there.

Thx for your help so far.
It's nice that watching the videos works now :)

**Comment by saerdnaer** [comment]
> Right now I have no button which I could use to try whether switching tracks/media files would even work. The buttons just aren't there.

Again: This is the native player of your browser, which is only shown when your browser has disabled javascript or can not load the MediaElementJS player. Is there some way to access to JavaScript console on that TV's browser to see error messages?


> The only annoying thing is how the tv chooses the source track to play
I can't choose the language. Sometimes it chooses the german dub (would be fine, I'm from germany, but I would prefer the original language), once it chose the french dub playing the download still doesn't work (the mp4 directly). I'm not sure how the tv chooses the track, it doesn't honor the order in the video tag

The rails server app writes nearly all recording formats as different sources into the video tag. The main download files contain multiple audio tracks. Most browsers try to select the best audio track based on the OS language, which often yields unexpected results when the user understand multiple languages e.g. german and english. As a workaround we added the the single language variants at the top – in this case `35c3-10018-deu….mp4` and `35c3-10018-eng….mp4`. Normally web browsers 

```html
<video class="video" controls="controls" data-id="6462" data-timeline="https://static.media.ccc.de/media/congress/2018/10018-hd.timeline.jpg" height="100%" poster="https://static.media.ccc.de/media/congress/2018/10018-hd_preview.jpg" preload="auto" width="100%">
  <source data-lang="deu" data-quality="high" src="https://cdn.media.ccc.de/congress/2018/h264-hd/35c3-10018-deu-Verhalten_bei_Hausdurchsuchungen.mp4" title="deu 1080p" type="video/mp4">
  <source data-lang="eng" data-quality="high" src="https://cdn.media.ccc.de/congress/2018/h264-hd/35c3-10018-eng-Verhalten_bei_Hausdurchsuchungen.mp4" title="eng 1080p" type="video/mp4">
  <source data-lang="deu-eng" data-quality="low" src="https://cdn.media.ccc.de/congress/2018/webm-sd/35c3-10018-deu-eng-Verhalten_bei_Hausdurchsuchungen_webm-sd.webm" title="deu-eng 576p" type="video/webm">
  <source data-lang="deu-eng" data-quality="high" src="https://cdn.media.ccc.de/congress/2018/webm-hd/35c3-10018-deu-eng-Verhalten_bei_Hausdurchsuchungen_webm-hd.webm" title="deu-eng 1080p" type="video/webm">
  <source data-lang="deu-eng" data-quality="low" src="https://cdn.media.ccc.de/congress/2018/h264-sd/35c3-10018-deu-eng-Verhalten_bei_Hausdurchsuchungen_sd.mp4" title="deu-eng 576p" type="video/mp4">
  <source data-lang="deu-eng" data-quality="high" src="https://cdn.media.ccc.de/congress/2018/slides-h264-hd/35c3-10018-deu-eng-Verhalten_bei_Hausdurchsuchungen_hd-slides.mp4" title="slides deu-eng 1080p" type="video/mp4">
  <source data-lang="deu-eng" data-quality="high" src="https://cdn.media.ccc.de/congress/2018/h264-hd/35c3-10018-deu-eng-Verhalten_bei_Hausdurchsuchungen_hd.mp4" title="deu-eng 1080p" type="video/mp4">
  <track kind="metadata" label="thumbnails" src="https://static.media.ccc.de/media/congress/2018/10018-hd.thumbnails.vtt" srclang="unknown">
  <link href="/postroll/35c3-10018-verhalten_bei_hausdurchsuchungen" rel="postroll">
</video>```


> the only one that doesn't work is the 4th which is the only stream that is vp8 only (webm hd)
webm sd also has vp9 video in it and therefore it seems to work
Ah, yes – that one also includes a second video track – the lecture slides. Players behave even more unexpectedly, with these files whereby we recommend to use VLC on desktop PCs. 


Can you open a single language file directly in the browser (e.g. https://cdn.media.ccc.de/congress/2018/h264-hd/35c3-10018-deu-Verhalten_bei_Hausdurchsuchungen.mp4) and check if it is able to play this?

**Comment by Djfe** [comment]
I'll check that this weekend.
Interesting info so far. I'll look into Javascript and whether it's activated and so on.
and I might upload an image of how the actual video player and it's controls look like.

> Normally web browsers

Did you mean to finish that sentence? (looks like you started writing something and forgot to continue later on)

**Comment by saerdnaer** [comment]
Fixed.

**Comment by saerdnaer** [comment]
We are cleaning up old issues, please reopen if this issue is not done.
