### ISSUE TITLE
Adding an end screen/my contact info to my talk

### ISSUE THREAD

**Issue by emilyhammes** [voc/voctoweb#359]
In the youtube version of Artistic PCB design, can you add a link to my channel on the end screen (https://www.youtube.com/c/hammeshacks)? I have demo videos, assembly videos and troubleshooting videos for all the devices I show in my talk. It would be great if everyone who watches my talk to the end could easily find my other videos without searching.

**Comment by manno** [comment]
We could add the fahrplan link (event.link) to the [postroll](https://github.com/voc/voctoweb/blob/master/app/views/frontend/events/postroll.html.haml).

However I'm afraid to break the layout?

**Comment by manno** [comment]
Added Fahrplan link to postroll page.

**Comment by saerdnaer** [comment]
Related: #29
