### ISSUE TITLE
CSS Broken for old recordings

### ISSUE THREAD

**Issue by T3rminat0r** [voc/voctoweb#365]
Hi, 

it seems like the CSS is broken for old(er) Recordings:
https://media.ccc.de/v/26c3-3613-de-fnord-jahresrckblick_2009
(The Stream/Audio-Selection menu is free-floating below/within the video frame, unless in fullscreen)
![image](https://user-images.githubusercontent.com/9053174/50707577-8cb42880-1061-11e9-8356-2b00b176a481.png)

Tested on Windows 10, using Chrome, Firefox and even Edge

**Comment by saerdnaer** [comment]
Side effect of https://github.com/voc/voctoweb/commit/0c72aedc2b1be3abb5e17ff31026fa56731dd32f
