### ISSUE TITLE
Play/Pause using space bar doesn't work under Firefox on Mac

### ISSUE THREAD

**Issue by Foaly** [voc/voctoweb#366]
Using Firefox (64.0) on Mac (10.13.6) it is not possible to start/pause a video using the space bar. It does works in Safari on Mac and as far as I am aware also with other browsers on other platforms. It would be great if this could be fixed :)

**Comment by saerdnaer** [comment]
We should redirect key board events like spacebar and left/right arrow keys from root document directly to the player, and not only we the player has the focus.

**Comment by Foaly** [comment]
This sounds like a great idea! :) Maybe its just me, but I am very used to starting a video by just hitting space.

**Comment by Foaly** [comment]
🎉 Thank you very much :)
