### ISSUE TITLE
Move timelens timeline below player (on small screens)

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctoweb#370]
It think we should move Timelens' timeline below the player when we have enough vertical space, c.f.
screenshots below.I would propose the break point at 500px screen width.

@blinry Do you have an better idea or could you even provide a PR?

<img src="https://user-images.githubusercontent.com/40266/50847715-921bb680-1372-11e9-9008-80e2318a1a2a.png" width="200" /> <img src="https://user-images.githubusercontent.com/40266/50843866-d2c30200-1369-11e9-82f5-05c1a33fcd49.PNG" width="200" />

**Comment by blinry** [comment]
I do like the idea! In fact, it should probably be default behaviour for MediaElement.js to offer a wider timeline (in a different line than the other controls) on narrow screens. Implementing this won't be trivial, but I'll keep it in mind! :)
