### ISSUE TITLE
Firefox Slideshow bx-pager-item verschwindet

### ISSUE THREAD

**Issue by famfop** [voc/voctoweb#371]
Klicke ich (unter Firefox Nightly 65.0a1) in der Slideshow auf ein links vom aktuell weißen bx-pager-item liegenden Punkt, springt die Slideshow zu diesem. Nun wandert der Punkt ja nach einiger Zeit von alleine weiter: Dann wird zunächst der ursprünglich angeklickte Punkt schwarz und erst beim nächsten Weiterwandern wieder sichbar.

**Comment by Necr0** [comment]
Entweder der Fehler hat sich selbst durch das Update der Slideshow  und ist kein Bug sondern ein eher ungünstiges Feature, dass hier gemeldet ist. Pull Request kommt in Kürze.
https://github.com/voc/voctoweb/blob/200275b3a82d1879f00bf75cd83eb94bbf95a6d3/app/assets/stylesheets/jquery.bxslider.css.scss#L83-L87
Diese CSS Regel ist eher ungünstig und ist explizit dafür da das beschriebene Verhalten zu verursachen.
