### ISSUE TITLE
Comment / Note field per event

### ISSUE THREAD

**Issue by derpeter** [voc/voctoweb#373]
If events / recordings have technical issues (audio, video ...) we have no good way to tell the the user that we know about this. This results in many reports of the issue. It would be good to have a comment / note / warning filed which can be filed if an event has an known issue. 
I believe it would be good to display this on top or below the video player. Maybe even highlighted with an color.

Putting it in the description will probably be not that effective as users will not always notice it.

**Comment by QbDesu** [comment]
![image](https://github.com/user-attachments/assets/409bfe27-94ad-463c-a2ae-259fb008df91)
Implemented in 6111689
