### ISSUE TITLE
Make link to GitHub more prominent

### ISSUE THREAD

**Issue by rugk** [voc/voctoweb#374]
I literally tried to find a way to report a bug yesterday and did not manage to find any link on the site (looked at footer or so)…

So I ended up [reporting it via webcompat](https://github.com/webcompat/web-bugs/issues/23952). (BTW, feel free to comment there, the repo owners can possibly move it here with that nice new move issue feature… or I just copy/paste)
Just now, I noticed this issue tracker.

Thus, I guess you should make the GitHub link more visible. It's at the bottom of a very long info page – _who_ looks there…? :thinking:

**Comment by saerdnaer** [comment]
I think the current solution deployed today, should resolve this issue – otherwise reopen with an concrete proposal.
