### ISSUE TITLE
35c3 podcast feeds for mp3 and opus are empty

### ISSUE THREAD

**Issue by Jonny007-MKD** [voc/voctoweb#379]
Both podcast feeds for mp3 and opus do not contain any item.
https://media.ccc.de/c/35c3/podcast/opus.xml
https://media.ccc.de/c/35c3/podcast/mp3.xml

**Comment by saerdnaer** [comment]
Side effect of https://github.com/voc/voctoweb/commit/ebcc8acd7732889de63be93ae8dcc291c1000931#diff-ae3e2ee0b7be3e93a45e8a2d06d2bf37R17
