### ISSUE TITLE
Support metadata for reference management software

### ISSUE THREAD

**Issue by eest9** [voc/voctoweb#387]
I struggle every time when I want to add talks to my reference management software (Zotero). It gets every time only the title without the speaker names, conference name and dates. This is because the metadata isn't structured in a way such a software could handle correctly. Therefore I would recommend to add the metadata in the [DCMI Standard](http://dublincore.org/documents/2008/08/04/dc-html/)
for alternative solutions see https://www.zotero.org/support/dev/exposing_metadata but I'm unsure how other reference management software like citavi would handle other formats.

**Comment by saerdnaer** [comment]
As of now we expose the metadata via [OpenGraph](http://ogp.me). What kind of attributes would you like us to add? Can you provide a screenshot about the current situation in Zotero or Citavi?
```html
<title />media.ccc.de - Introduction to Deep Learning</title>
<meta name="author" content="CCC" /> 
<meta name="description" content="This talk will teach you the fundamentals of machine learning and give you a sneak peek into the internals of the mystical black box. You..." />
<meta name="keywords" content="35c3, 9386, Science, Chaos Computer Club, Video, Media, Streaming, TV, Hacker" />
<meta property="og:title" content="Introduction to Deep Learning"  />
<meta property="og:type" content="video.other" />
<meta property="og:url" content="/v/35c3-9386-introduction_to_deep_learning" />
<meta property="og:image" content="https://static.media.ccc.de/media/congress/2018/9386-hd_preview.jpg" />
<meta property="og:video" content="https://cdn.media.ccc.de/congress/2018/h264-hd/35c3-9386-eng-Introduction_to_Deep_Learning.mp4" />
<meta property="og:description" content="This talk will teach you the fundamentals of machine learning and give you a sneak peek into the internals of the mystical black box. You..." />
[…]
<link rel="alternate" title="media.ccc.de oembed profile" type="application/json+oembed" href="https://media.ccc.de/public/oembed?url=https%3A%2F%2Fmedia.ccc.de%2Fv%2F35c3-9386-introduction_to_deep_learning" /></head />
```

**Comment by eest9** [comment]
I miss the date of the presentation and the name of the presenter. These 2 information are required in any form of citation.
![bildschirmfoto von 2019-02-03 23-12-48](https://user-images.githubusercontent.com/11019106/52183577-67097300-2809-11e9-8dc7-f95692b77396.png)

**Comment by saerdnaer** [comment]
Did you select the "Type" manually, and modify the title? I personally would rather classify it as presentation, and not as video recording. 

So we have multiple options:
* Dublin Core 
* Highwire [[1]](https://scholar.google.com/intl/en/scholar/inclusion.html#indexing)  [[2]](https://www.monperrus.net/martin/accurate+bibliographic+metadata+and+google+scholar)
* OpenGraph (not supported by referenced citation programms)


Dublin Core looks over-specified, when somebody comes up with clear examples, maybe...

```xml
<meta name="citation_title" content="Introduction to Deep Learning">
<meta name="citation_author" content="Author A">
<meta name="citation_author" content="Author B">
<meta name="citation_publication_date" content="2018/12/27">
<meta name="citation_conference_title" content="35C3">
```
Actually, when reading [1] there are also some DC examples:
 
```xml
<meta name="DC:title" content="Introduction to Deep Learning">
<meta name="DC:creator" content="Author A">
<meta name="DC:creator" content="Author B">
<meta name="DC:date" content="2018/12/27">
```

OpenGraph, just for completion of this survey, also specifies a `video:release_date`, http://ogp.me/#type_video.movie – but as persons only a director and not a presentor, speaker or author...

BTW: Can you check how your software reacts when importing https://av.tib.eu/media/39340 ? Which client are you using exactly?

**Comment by eest9** [comment]
I didn't choose anything manually in this example. I would also expect it to be a presentation. I'm not sure but I think it might come frome `<meta property="og:type" content="video.other" />`

I'm using Zotero with the Firefox plugin.

![bildschirmfoto von 2019-02-04 01-04-24](https://user-images.githubusercontent.com/11019106/52184832-ece0ea80-2818-11e9-9ec9-a328696baca0.png)
![bildschirmfoto von 2019-02-04 01-03-32](https://user-images.githubusercontent.com/11019106/52184833-ece0ea80-2818-11e9-8653-960b47872347.png)

This is way better! only the type should be a presentation instead of a document

**Comment by eest9** [comment]
I didn't recognize it yesterday, but the talks get DOI-Numbers? Because Zotero is able to get metadata from DOI-References. 🤔
Do only Congress-Talks get DOI-Numbers? Because then my issue would still be relevant.

**Comment by saerdnaer** [comment]
See #232 for more information about the DOIs.

**Comment by saerdnaer** [comment]
@eest9 I added author and publish_date to the header metadata – could you check if the import is now more useful?

**Comment by eest9** [comment]
It works for the author but not for the date.

**Comment by Necr0** [comment]
As you can see in the issue that referenced this issue this is probably a bug on Zotero's side, which does seem to have a bug that breaks support for OpenGraph video and music metadata.
