### ISSUE TITLE
Allow to filter popular videos by year

### ISSUE THREAD

**Issue by Nudin** [voc/voctoweb#388]
The list of most popular videos right now contains nearly only videos from 2015, this is logical, since the number of views tends to be older the older a video is. #207 also adressed this suggesting to sort the videos by something like "view_count/age". Another approach that might be easier to implement and even more practial is to allow to filter the list by upload year. This way one could watch the 20 most popular videos from 2015, 2016, 2017, … – a further benefit of this is that it allows to easily find new popular videos that have been uploaded since the last visit.

**Comment by saerdnaer** [comment]
Duplicate of #14

**Comment by Nudin** [comment]
Closed by #465
