### ISSUE TITLE
Add NewPipe to the list of supported apps

### ISSUE THREAD

**Issue by theScrabi** [voc/voctoweb#389]
The [recent version](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.16.0) of [NewPipe](https://newpipe.net) finally supports media.ccc. I wanted to ask it you could at the app the the list of supported apps at your [about](https://media.ccc.de/about.html) page.

c.f. https://github.com/TeamNewPipe/NewPipe/pull/2083

**Comment by derpeter** [comment]
Thanks for adding us to NewPipe, as you already found the right repository, could you send us a pull request or at least the text you want to see on the about page.

**Comment by theScrabi** [comment]
All right

**Comment by saerdnaer** [comment]
Simply add it below https://github.com/voc/voctoweb/blob/master/app/views/frontend/home/about.haml#L84-L86

**Comment by saerdnaer** [comment]
Implemented in PR #391
