### ISSUE TITLE
API responds with '204 No Content' for some events

### ISSUE THREAD

**Issue by gdetrez** [voc/voctoweb#390]
First of all, media.ccc.de is awesome and the API is a pleasure to use.  Thatks a lot for all your work!

i came accross an issue that I think might be a bug but it migh also be me who isn't using the API properly.  For some events, the API responsds with a `204 No Content` when using the event slug. E.g.:
```
❯❯❯ curl https://api.media.ccc.de/public/events/rustcologne.2018.06.share-secrets-safely -I
HTTP/2 204 
server: nginx/1.10.3 (Ubuntu)
date: Wed, 27 Mar 2019 11:20:56 GMT
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-request-id: 887c4027-5135-4676-85f1-c74e0f503cdd
x-runtime: 0.003831
front-end-https: on
x-cache: MISS edge
```
(the response body is, appropriately, empty).

For most event however, the API provides the expected JSON data when queried the same way (i.e. using the slug and not the guid):
```
 ❯❯❯ curl https://api.media.ccc.de/public/events/rustfest18-3-immutable_data_structures_and_why_you_want_them

{
    "guid":"1adcd4eb-7655-5f62-9917-add6bf2b2eee",
    ... <lot's of json>
}
```

I noticed that all the events for which I get 204 have `.` (dots) in their slug, could that be the issue?

**Comment by manno** [comment]
Yes, that's indeed a bug

https://stackoverflow.com/questions/23672831/how-to-handle-dot-character-in-rails-resources-routes
