### ISSUE TITLE
Default resolution to 576p to reduce energy consumption

### ISSUE THREAD

**Issue by gittaca** [voc/voctoweb#396]
Watching media.ccc.de recordings regularly, I rarely encounter slide sections that contain lost of text, complex graphics, or other reasons to switch the stream to 1080p. It seems the speakers thoroughly observe the advice on good presenting ;-) What's your experience?

As shown in [Hoque et al (2013), Fig. 14](https://users.aalto.fi/~siekkine/pub/wowmom_final.pdf), the power consumption of lower-res streaming is measurably lower, and lower for MP4 compared to WebM. At least on mobile devices, thus:

a) How popular are those for accessing media.ccc.de?
b) Does anyone know similar measurements on larger-screen devices?

[theShiftProject.org's video streaming report](https://theshiftproject.org/en/article/unsustainable-use-online-video/) also highlights this issue. Although, I can't answer all of these questions definitely, I would like to suggest media.CCC.de to take the cautionary approach here: While leaving the 1080p option available for relevant cases, please consider setting 576p as the default, because it likely reduces energy consumption both in the back-end and on the user's side.

**Comment by gittaca** [comment]
The HD/SD default is defined here, isn't it?

https://github.com/voc/voctoweb/blob/a73fb49bafe032b0ee17c760b6d97975a121cd90/app/models/frontend/recording.rb#L14-L19

**Comment by saerdnaer** [comment]
No, it is actually the order of the individual video sources in die `<video>`-Tag. In general this is the order in which the individual recordings of event (aka lecture) were created in the backend, but for conferences with translations, the original language version gets sorted to the top:

https://github.com/voc/voctoweb/search?q=videos_sorted_by_language&unscoped_q=videos_sorted_by_language

https://github.com/voc/voctoweb/blob/8bfa295eda39448a099b3e4032630e0dcc06614a/app/models/frontend/event.rb#L73-L76

With addition of timelens, the publishing of the master file event got delayed to in some cases now the sd version is already at the top of the list, if there are no translations. :-)

In general it would prefer if the player would actually decide based on the current viewport which version to load... we still have to evaluate/test if we should complete switch to Clapr Player, c.f. https://github.com/voc/voctoweb/issues/264
