### ISSUE TITLE
Create-or-Replace API for Recordings

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctoweb#40]
The private API should offer a Create-or-Replace call which would allow a simple implementation of re-releases in the publishing-script.

cc @derpeter

**Comment by manno** [comment]
The existing CRUD controllers [app/controllers/api/recordings_controller.rb](https://github.com/voc/media.ccc.de/blob/master/app/controllers/api/recordings_controller.rb) should handle this.
Note this is a [InheritedResources](https://github.com/josevalim/inherited_resources) controller, so actions like index and show are inherited.

1. Call show with id of recording
2. Call either create or update(id)
3. Call download(guid)

Problem is, the release script doesn't know the id and doesn't have state. Though the id is returned upon creation. The guid is known to the script.

I could add a 'search' method to get these ids by folder/filename. One could ask the public API, but there are other problems (#43).
In the long run I want to replace the current API (#44).

**Comment by MaZderMind** [comment]
My Idea was to match based on the GUID which we know is required to publish on media.

The release-script would have to perform multiple interactions with the API on each release:
 - search for existing event based on event-id
 - search for existing recording on this event based on guid
 - update or delete recording based on search-result
 - trigger download based on guid

which I feel would be better bundled in the API-Controler. (Re)Publish a Recording onto an Event is such a common use-case that having special logic for that seems reasonable to me.

**Comment by MaZderMind** [comment]
well, it seems the releasing script can already do this, closing this ticket.

**Comment by derpeter** [comment]
to be correct it cant do that but we know how we want to handle it.

**Comment by manno** [comment]
this is related to #54  public api: improve documentation

**Comment by manno** [comment]
Please open another ticket if you need specific functionality in the private API.

**Comment by saerdnaer** [comment]
An sich kann die API alles, das ist eher ein Problem für den Tracker/das releasing Skript -> https://github.com/voc/publishing/issues/8
