### ISSUE TITLE
long titles break start page layout

### ISSUE THREAD

**Issue by derpeter** [voc/voctoweb#401]
See screenshot below left content block overlaps with the spacer.

![mediabroken](https://user-images.githubusercontent.com/599344/65692061-387b2980-e072-11e9-93d3-6957c82cb1f7.png)

**Comment by saerdnaer** [comment]
Tatsächlich ist das eher das zu große Thumbnail bzw. hier das Relive-Video mit Fallback auf das Konfernz-Logo das die Ansicht kaputt macht. Setzt man auf das Thumbnail nen max-width von 62px sieht es okay aus:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/40266/65796787-cc7deb80-e16d-11e9-9881-bea082c72e82.png">
