### ISSUE TITLE
mobile view shows no thumbnails but timelense

### ISSUE THREAD

**Issue by bjoern-r** [voc/voctoweb#402]
As seen in the picture,
the conference view does not show thumbnails but instead the sort of useless timelense graphs..

![Screenshot_20190926-153458](https://user-images.githubusercontent.com/5096000/65694636-78441000-e076-11e9-9a9d-09e5c4a86f7d.png)

**Comment by derchrisuk** [comment]
Das liegt am Viewport.
Wenn du das Telefon drehst wird auch ein Thumbnail angezeigt.

**Comment by saerdnaer** [comment]
Ich glaub das ist ein Feature... :-)

**Comment by meise** [comment]
Ich find das okay.

**Comment by bjoern-r** [comment]
also ich find ja thumbnails aussagekräftiger als die timelens streifen
