### ISSUE TITLE
media.ccc.de/c/vcfb19 does not count video views

### ISSUE THREAD

**Issue by cyberfritz** [voc/voctoweb#419]
This is not on the software, but on the video page for a specific event. 

https://media.ccc.de/c/vcfb19
![image](https://user-images.githubusercontent.com/40266/67093074-1415f700-f1b1-11e9-8c3c-2cb4d124b47c.png)

**Comment by saerdnaer** [comment]
Looks like all new views are no longer counted... @manno Do you have any idea why?

**Comment by saerdnaer** [comment]
@cyberfritz fixed, I accidentally cleaned our API tokens to extremely... 😅
