### ISSUE TITLE
OAI-PMH support

### ISSUE THREAD

**Issue by Necr0** [voc/voctoweb#424]
Would anyone oppose providing an endpoint for the Open Archives Initiative Protocol for Metadata Harvesting?

**Comment by saerdnaer** [comment]
URL?

**Comment by Necr0** [comment]
Oops, I completely forgot: https://www.openarchives.org/OAI/2.0/openarchivesprotocol.htm

**Comment by saerdnaer** [comment]
I looked into the spec and are not really interested in implementing such an old, out of date API – which is not even Restful, isn't it? 
If somebody really needs this, I would recommend to create a proxy service using the GraphQL or public REST API.
