### ISSUE TITLE
Podcast feed for event has other events content

### ISSUE THREAD

**Issue by jfowl** [voc/voctoweb#427]
I wanted to get the denog11 videos as a mP4 HD Podcast. The XML for it contains 34C3 videos and description. The sd one points to metanok18, etc.

The switch up seems to be consistent as I got the same wrong results from multiple distinct IPs

**Comment by saerdnaer** [comment]
Which feed URL did you use?

**Comment by jfowl** [comment]
I did test it again and it is now working. Thanks ;)
