### ISSUE TITLE
Add Mastodon Sharing Button

### ISSUE THREAD

**Issue by ThomasLeister** [voc/voctoweb#438]
Hi,

there are already "share" buttons on the player page for Twitter, Facebook, Email and even Diaspora. It would be nice to have another button for Mastodon, which many CCC members are using nowadays :-)

**Comment by saerdnaer** [comment]
@derchrisuk Can you push the current state of your solution into a feature branch?

**Comment by QbDesu** [comment]
@lukas2511 hacked in a solution for now. readily available libraries are unfortunately kinda ass.
