### ISSUE TITLE
bad urls for "Delta Chat" talk from 36c3

### ISSUE THREAD

**Issue by unwiredben** [voc/voctoweb#439]
for talk ID 18a492b2-6219-5b95-a48d-b03944b75739, "Delta Chat: e-mail based messaging, the Rustocalypse and UX driven approach [YBTI/wefixthenet session]", several of the URLs are bad -- they're missing the oio folder in the URLs, like the thumb_url that is https://static.media.ccc.de/media/congress/2019/154-hd.jpg. 

`{"guid":"18a492b2-6219-5b95-a48d-b03944b75739","title":"Delta Chat: e-mail based messaging, the Rustocalypse and UX driven approach [YBTI/wefixthenet session]","subtitle":null,"slug":"36c3-oio-154-delta-chat-e-mail-based-messaging-the-rustocalypse-and-ux-driven-approach-ybti-wefixthenet-session-","link":"https://talks.oio.social/36c3-oio/talk/WSLWVM/","description":"Delta Chat is an e-mail instant messenger that is just becoming available on all platforms. \nUnlike other offerings, Delta Chat is no platform and operates no own servers. \nInstead it uses existing SMTP/IMAP servers to send and receive messages.\nWe'll talk about the current development status on all platforms, our new \nRust-core based approach, our decentralized e2e-encryption facilities (not requiring \nkeyservers, and safe against active attacks) and how we are generally driving\ndevelopments from UX and security perspectives.  We also aim to showcase\n\"burner accounts\", a new concept that we are developing and discussing\nwith activists in eastern european countries and asian cities.","original_language":"eng","persons":["dvn"],"tags":["36c3-oio","154","2019","Resilience & Sustainability","OpenInfrastructureOrbit"],"view_count":14,"promoted":false,"date":"2019-12-29T17:40:00.000+01:00","release_date":"2020-01-02","updated_at":"2020-01-02T23:30:12.187+01:00","length":2016,"duration":2016,"thumb_url":"https://static.media.ccc.de/media/congress/2019/154-hd.jpg","poster_url":"https://static.media.ccc.de/media/congress/2019/154-hd_preview.jpg","timeline_url":"https://static.media.ccc.de/media/congress/2019/154-hd.timeline.jpg","thumbnails_url":"https://static.media.ccc.de/media/congress/2019/154-hd.thumbnails.vtt","frontend_link":"https://media.ccc.de/v/36c3-oio-154-delta-chat-e-mail-based-messaging-the-rustocalypse-and-ux-driven-approach-ybti-wefixthenet-session-","url":"https://api.media.ccc.de/public/events/18a492b2-6219-5b95-a48d-b03944b75739","conference_url":"https://api.media.ccc.de/public/conferences/36c3","related":[]}
`

**Comment by saerdnaer** [comment]
Manually fixed in the database, images path prefixes have to be implemented in the publishing script, c.f. https://github.com/voc/voctopublish/issues/82
