### ISSUE TITLE
video position thumbnail takes mouse input after disappearing

### ISSUE THREAD

**Issue by gimbar** [voc/voctoweb#445]
If you move your mouse over the timeline you get a tiny thumbnail which shows the video frame at that point. This thumbnail vanishes if the mouse cursor leaves the player to the lower edge.
But it still takes mouse input.

Move the mouse around the timeline and click the area -> video jumps to the position your mouse last visited on the timeline without toggling play/pause.
The voctocat-play-pause-icon is affected by this to: It toggles when the cursor enters the player area but doesn't in the area formerly used by the thumbnail.

This happens during play and pause of the video.

I'm using Firefox 72.0.1

**Comment by gimbar** [comment]
I'm able to reproduce this behaviour in Chrome 79.0.3945.117.

**Comment by telegnom** [comment]
I was able to reproduce this behavior in Mozilla Firefox 73.0b4 as well.

**Comment by saerdnaer** [comment]
@blinry Do you have time to look into this?
