### ISSUE TITLE
Text overlaps on small screen resolutions

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [voc/voctoweb#459]
I was [searching for "Julian Oliver"](https://media.ccc.de/search/?q=Julian+Oliver) at media.ccc.de and there is a text overlap at the oldest entry [(see picture).](https://i.imgur.com/DPumVWI.png)

![](https://i.imgur.com/DPumVWI.png)

Testing with Chromium 80.0.3987.149 (Developer Build) built on Debian 10.3, running on Debian 10.3 (64-bit). My screen resolution 1366 x 768 px.

**Comment by saerdnaer** [comment]
should be fixed now, reopen/comment if otherwise

**Comment by saerdnaer** [comment]
![Uploading image.png…]()
