### ISSUE TITLE
Make frab event IDs searchable via slug

### ISSUE THREAD

**Issue by timpritlove** [voc/voctoweb#46]
The event ID is the only unique item about an event. However currently the event IDs are not included on the event pages and are not searchable via the search box.

Feature requests:
- include the event ID clearly visible (emphasizing its importance) on the event page
- allow searching for event IDs via the search box

**Comment by manno** [comment]
Actually there is a longer database independent guid to identify talks. This seems highly frab specific and is not useful for other videos.

**Comment by timpritlove** [comment]
You mean it should not be possible to search for event IDs?

**Comment by manno** [comment]
We should use the events title or slug.

Frabs internal database IDs are not stable, i.e. they might change if we re-create the database. This actually happened several times. In the past we maintained lists of mappings, new id -> old id. That was a huge problem for all our scripts.

Frab still exposes the event id in the URL of an events detail page, but generally the event id is not exposed to other systems (via public schedule).

Furthermore media.ccc.de is meant as a frontend to lots of different video files, not just conferences using frab. 

media.ccc.de actually doesn't know the ID... well, this isn't entirely true. Since the ID is exposed in the URL and media.ccc.de knows the link to the fahrplan page, we could search the event.link value to realize the search? (ping @florolf @MaZderMind)

**Comment by timpritlove** [comment]
All I ask for is being able to search for an important event property and having it displayed. it exists and it is meaningful to the event. it does not need to be unique to grab internally. 

However: the initial idea behind the event ID within Pentabard was it to be unique. Adding the event slug it can still be made it into something unique: "32C3:7304" could be as unique as necessary.

**Comment by saerdnaer** [comment]
Just for reference: We are talking about adding the line `'event.link',` at https://github.com/voc/media-search-prototype/blob/master/server/search.pl#L49 ?

**Comment by florolf** [comment]
I don't think extracting information from `event.link` is in any way a good idea. Parsing the slug seems dubious, too. The format of those things is too volatile to be relied upon (or rather: Nobody will think about the poor script parsing those values when deciding to change the format). Those values are not an API. If we want to search for a field, it should be cleanly exposed by media.

**Comment by manno** [comment]
@florolf Not extracting, just searching the URLs for sub strings?

**Comment by saerdnaer** [comment]
@florolf What speaks agains adding the slug to the search index? Shouldn't the user get a matching result when she enters the full slug?

**Comment by timpritlove** [comment]
Please consider an "event ID" to be a major internal meta datum of any recording. It's something that exists, has a meaning and can be super helpful when being search for, referenced etc. The basic iead for the Pentabard Event ID was to be public and highly visible, not an internal and exchangeable reference code hidden from the user.

**Comment by derpeter** [comment]
I would agree on that. For all events where we still got the schedule this could possibly updated more or less automatically. Even if the ID is no unique over all conferences and not all conference have that flag it would by very help full for things where the i.e. the name is not known.
At least we could consider adding it to the tags what would be not that helpfull and hart to do for the already released stuff but better then nothing.

@timpritlove do you think we could get some of your follwers minions to help a little with media. Pull request are highly appriciated

**Comment by saerdnaer** [comment]
TODO: add slug to https://github.com/voc/voctoweb/blob/master/app/models/concerns/elasticsearch_event.rb#L15

**Comment by saerdnaer** [comment]
Looks like we missed the correct option: https://media.ccc.de/search/?q=7551

**Comment by MaZderMind** [comment]
Well we added the field to the search but missed the serializer. fix incoming.
