### ISSUE TITLE
Postgres fails due to password in Docker

### ISSUE THREAD

**Issue by Nudin** [voc/voctoweb#464]
I wanted to set up a development environment as instructed in the README but ran into problems:
First I got an error that the postgres host couldn't be reached, in the output of docker-compose I found the error message of postres: "Error: Database is uninitialized and superuser password is not specified.".

~To fix this I tried adding ether `POSTGRES_HOST_AUTH_METHOD=trust` or `POSTGRES_PASSWORD=password` to the docker-compose file.
Now I run into the new issue that I get the error: `fe_sendauth: no password supplied`~

Not sure how to fix that. Can anyone help? Would be motivated fix some issues.

**Comment by Nudin** [comment]
This can be fixed by adding the following to `docker-compose.yml` in the postgres section:
```
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
```

I'm not sure what the security implications for a developing environment are.

**Comment by saerdnaer** [comment]
@Nudin Can you check if you run still into this problem, even with the updated docker-compose file on master?

**Comment by Nudin** [comment]
Fixed.
