### ISSUE TITLE
No editor for text body when editing/creating news

### ISSUE THREAD

**Issue by andibraeu** [voc/voctoweb#466]
When editing or creating news no editor for the news body appears, see screenshot attached.

![image](https://user-images.githubusercontent.com/1162168/81266740-95e24a80-9045-11ea-937f-7bfa3ce1e424.png)

I can get an editor if I get there from the frontend:

* Select an event
* go to backend via edit button
* Navigate to  news and add or edit an existing item

![image](https://user-images.githubusercontent.com/1162168/81267073-23be3580-9046-11ea-9a93-4263158394ac.png)

This is the voctoweb installation at media.freifunk.net

**Comment by saerdnaer** [comment]
Hi Andi,
yes the rich text editor is currently broken on all pages, you can workaround that with following change: https://github.com/voc/voctoweb/commit/8f862c34df83c14c55d994c7dd44253d25db4af6

**Comment by andibraeu** [comment]
thanks, that worked for now
