### ISSUE TITLE
GraphQL: Requesting images on lectures fails for related lectures

### ISSUE THREAD

**Issue by toto** [voc/voctoweb#471]
Requesting related lectures does not work if you try to retrieve the `images` field (it produces a 500 error)

```
query Query {
  lecturesRelatedTo(guid: "9f403b2e-e561-4e85-bb35-61c5e0d0c138") {
    nodes {
        images {
   	  thumbUrl
    	  posterUrl
  	}
    }
  }
}
```

the request for other fields works well

```
query Query {
  lecturesRelatedTo(guid: "9f403b2e-e561-4e85-bb35-61c5e0d0c138") {
    nodes {
      title
      guid
    }
  }
}
```

**Comment by toto** [comment]
I had another query fail when you request `nodes { images { anything } }`, so the problem is the image relation resolver

**Comment by saerdnaer** [comment]
@toto Thanks for the report, and sorry for the delay. Should be fixed now.
