### ISSUE TITLE
Decentralised streaming

### ISSUE THREAD

**Issue by KOLANICH** [voc/voctoweb#481]
Hi.

Do you know anything about torrent-like decentralized streaming? I mean do you know why all open-source solutions for that have failed?

**Comment by saerdnaer** [comment]
Please search for other tickets with keywords "torrent" or "peertube". For us our own HTTPS CDN is decentralised enough.

**Comment by KOLANICH** [comment]
I have already seen them. But Bit-Torrent and PeerPube are for sharing files, not streams. BTW, I have found something: [an IETF standard](https://tools.ietf.org/html/rfc7574) and even some impls, though I haven't yet managed to plug that into OBS and VLC - VLC doesn't like the raw UDP streams produced by OBS and FFMpeg, and OBS doesn't send into raw RTP without workarounds (like using `save` tab for actually streaming).

**Comment by derpeter** [comment]
No experience with the implementation / standard you mentioned, also not convince that p2p streaming is a useful technology at all. (probably this is not the place to discuss ;-) ). But maybe i can give you some leads to get it running: 

1) if  VLC is unhappy (happens to me most of the time) try ffplay or mpv. They use the ffmpeg code base so its more likely ffmpeg generated content can also be played back
2) OBS is pain regarding its outputs. To ease the pain (at least for your experiments) just put out rtmp or SRT and fetch that with ffmpeg. This way you get your output and ffmpeg can afterwards mux it in anything you want and you don't have to deal with the obs limitations

**Comment by KOLANICH** [comment]
>try ffplay or mpv

Thanks, I have already tried them, they work fine. The problem is that I cannot distribute it. VLC is one of little cross-platform players. The original plan was to create a bundle of a PPSPP impl and a wrapper getting the info from the source server and then starting VLC available in the system (it is available for GNU/Linux, *BSD, Windows, Android and iOS) with the needed params (even creating a local file, if needed).

>To ease the pain (at least for your experiments) just put out rtmp or SRT and fetch that with ffmpeg. This way you get your output and ffmpeg can afterwards mux it in anything you want and you don't have to deal with the obs limitations.

Thanks for the info, should try. Maybe even the following chain: `obs -> [rtmp] -> ffmpeg -> udp -> ppspp -> udp -> ffmpeg -> vlc`
