### ISSUE TITLE
Shortlink support

### ISSUE THREAD

**Issue by Kunsi** [voc/voctoweb#496]
Redirect `media.ccc.de/s/<talkid>` to proper URL

**Comment by saerdnaer** [comment]
fixed with https://github.com/voc/voctoweb/commit/5207e6c3d33ef6e424922dccd6edd8907cef6472 – you can either use the prefix with the local id, e.g. `https://media.ccc.de/v/rc3-49321` or the event UUID/GUID e.g. `https://media.ccc.de/v/be0fa4c9-32c1-5879-aecc-178dbf4fc6d0`
