### ISSUE TITLE
add plex-compatible, granular rss-feed

### ISSUE THREAD

**Issue by herrxyz** [voc/voctoweb#499]
Hello,
I would love to be able to add streams to Plex mediaplayer. Maybe the easiest way would be to import an rss-feed into Plex podcast functionality, but unfortunately it is not able to import current rss-feeds from media.ccc .
different rss-feeds for events would also be great

**Comment by saerdnaer** [comment]
@herrxyz Klick mal oben rechts auf den RSS Feed Button auf der jeweiligen Konferenz-Seite, da gibts diese spezifischen Feeds z.B. https://media.ccc.de/c/rc3/podcast/mp4-hq.xml 

![image](https://user-images.githubusercontent.com/40266/103709187-4e380800-4fb2-11eb-8e04-3192615e26db.png)
