### ISSUE TITLE
Playback broken

### ISSUE THREAD

**Issue by mro** [voc/voctoweb#500]
e.g. https://media.ccc.de/v/rc3-857362-die_rosarote_brille_des_fediverse doesn't play prbly due to network errors visible in javascript console.

Can you have a look into it, thx!

**Comment by davidak** [comment]
the video is not actually published. that is just a automatic placeholder. even the URL will probably change... (https://github.com/voc/voctoweb/issues/502) just wait for a proper release

(congratulation to the 500th issue :sparkles: )

**Comment by saerdnaer** [comment]
@lukas2511 Lässt sich da die m3u8 Playlist reparieren?

**Comment by lukas2511** [comment]
fixed, da lief ein ffmpeg neu an der es nicht sollte und hat die playlist gewiped
