### ISSUE TITLE
HTTP status code 406 if tag contains dot

### ISSUE THREAD

**Issue by lujoga** [voc/voctoweb#501]
If there is a `.` (Full Stop, U+002E) in a tag (e.g. [franconian.net talks](https://media.ccc.de/c/rc3/franconian.net%20talks)), Voctoweb responds with status [406 Not Acceptable](https://http.cat/406).

In Firefox, this can simply be "fixed" by manually replacing the dot with `%2E`. Chrome will just replace `%2E` with `.` again and continue failing.

**Comment by muellermartin** [comment]
Apparently the fix only works in Firefox, but not in Chrome or Safari.

Tested browser versions on macOS:
- Chrome: Version 89.0.4389.82 (Official Build) (x86_64)
- Safari: Version 14.0.3 (14610.4.3.1.6)

**Comment by lujoga** [comment]
I can confirm that this is still the case for the following versions:
* Chrome: `Version 88.0.4324.190 (Offizieller Build) (64-Bit)` on Windows
* Chrome: `Version 88.0.4324.182 (Offizieller Build) (64-Bit)` on Linux
* Chromium: `Version 88.0.4324.182 (Offizieller Build) Arch Linux (64-Bit)`

Note that I mentioned in the original comment that Chrome will just replace the percent-encoding with a plain dot. This happens *before* sending it to the server, which is why it does not suffice to replace `.` with `%2E` in links.

**Comment by saerdnaer** [comment]
Hmm, should I simply rename the existing talks which contain a dot? The problem right now is that for the Rails URL router, the dot has a special meaning (selecting the response format)

**Comment by lujoga** [comment]
I just looked at `config/routes.rb` and it looks like for `/v/` routes this issue has already been fixed by adding `:constraints => { slug: %r'[^/]+' }` ([see also](https://guides.rubyonrails.org/routing.html#dynamic-segments)). Would it be possible to implement this fix for `/c/` routes as well?
