### ISSUE TITLE
Add audio player

### ISSUE THREAD

**Issue by derpeter** [voc/voctoweb#505]
While it is possible to have events that have only audio files this results in a page with a warning an no player.
e.g. https://media.ccc.de/v/rc3-9-you_can_t_reform_that_shit

It would be nice to have to have an audio player there. 
We might also want an audio player for releases that have video so people with low bandwidth or no intertest in the video part can play it in the browser. I"m not sure whats the best way to do that would be, maybe tabs as on streaming.media.ccc.de

**Comment by saerdnaer** [comment]
@derpeter Can you upload a thumbnail for audio only releases?

**Comment by derpeter** [comment]
usually it defaults to no the conference logo. Not sure where to generate a thumb of.
