### ISSUE TITLE
RSS feeds not updating since June

### ISSUE THREAD

**Issue by odahoda** [voc/voctoweb#569]
Hi,

the feeds linked from media.ccc.de (e.g. https://media.ccc.de/updates.rdf or https://media.ccc.de/podcast-hq.xml) only contain items up to 2021-06-23, whereas the homepage and https://media.ccc.de/recent show more recent videos.

https://media.ccc.de/podcast-hq.xml does contain the very suspicious element:
`<lastBuildDate>Wed, 30 Jun 2021 22:03:07 -0000</lastBuildDate>`

I see the code that produces the feeds, but I don't speak ruby, so I can't trace back to where and how this is supposed to be called...

-Ben

**Comment by lukas2511** [comment]
Seemed to be a deployment issue (sidekiq wasn't working). Feeds should be updated now :)
