### ISSUE TITLE
"-" at the end of an url

### ISSUE THREAD

**Issue by ruru4143** [voc/voctoweb#578]
roday i send this url to a fellow friend on Signal: `https://media.ccc.de/v/content18-52-berlin-werbefrei-no-advertisement-in-public-spaces-`.
My friend coudn't open it because the signal andriod app didn't take the trailing "-" character as part of the domain.

**Comment by saerdnaer** [comment]
the slug is generated by the publisher generating the schedule.xml – it is his/her responsibility to trim titles, not a problem of voctoweb. 

Neither or less we shoud enhance the 404 site (in this case https://media.ccc.de/v/content18-52-berlin-werbefrei-no-advertisement-in-public-spaces) to automatically redirect to the corresponding talk using the search, c.f. https://github.com/voc/voctoweb/issues/496 and https://github.com/voc/voctoweb/issues/502

**Comment by saerdnaer** [comment]
fixed by prefix match
