### ISSUE TITLE
[content] German and English audio channels are mixed in single channel

### ISSUE THREAD

**Issue by raffaelj** [voc/voctoweb#586]
Video: https://media.ccc.de/v/rc3-2021-fem-443-battle-of-render-engine

The first 8 seconds are German only, than the English translation starts on top of the German voice.

Tested with web player and also with downloaded mp4 files (1080p, 576p).

**Comment by airtower-luna** [comment]
I've encountered the same problem in this video: https://media.ccc.de/v/rc3-2021-fem-186-das-ist-doch-ha

**Comment by saerdnaer** [comment]
```
[14:34:22] <thunfisch> glitter-corn: known issue with all fem talks, will be fixed. thanks for reporting.
```

**Comment by saerdnaer** [comment]
The FeM channel resolved the issue and published new versions without this bug.
