### ISSUE TITLE
Allow to specifiy language for podcast feeds.

### ISSUE THREAD

**Issue by ypid** [voc/voctoweb#61]
Hi

It seems that currently, the podcasts feeds (example: https://koeln.media.ccc.de/c/32c3/podcast/mp3.xml) somewhat randomly refer to the available language versions. Would it be possible to add lets say a parameter `lang` with which users can select the languages they want?

Possible values:
- 'de' -> German
- 'en' -> Englisch
- 'native' -> untranslated original audio
- 'en,de' -> Prefer English and fallback to German if no English version is available.

**Comment by saerdnaer** [comment]
We decided that we partly fix this issue by enforcing usage of the native, untranslated audio files for the current podcast feeds. Dynamic language selection via a url parameter would require an rewrite of the podcast feed generator code.

**Comment by saerdnaer** [comment]
closing this now, comment if you still need this feature
