### ISSUE TITLE
Data quality

### ISSUE THREAD

**Issue by TobiX** [voc/voctoweb#62]
As I wrote in cccc/plugin.video.media-ccc-de#8, currently there is not enough data to make an automated decision on which recording to select in which situation. Looking at the "download" tab of my preferred sample: 
https://media.ccc.de/v/31c3_-_6212_-_en_-_saal_1_-_201412282330_-_heartache_and_heartbleed_the_insider_s_perspective_on_the_aftermath_of_heartbleed_-_nick_sullivan#download - This is a collection of videos and nobody knows which to select. SD/HD distinction seems to be lost for some recodings and web versions aren't filtered out.

![temp](https://cloud.githubusercontent.com/assets/40266/12822238/5f0f7b88-cb67-11e5-8a34-6a95ac044730.png)

**Comment by manno** [comment]
**Language:** No idea why the language is wrong. I could try to extract it from the filename. Unless @voc wants to test the new admin API. I no longer inherit all the actions so you can see more clearly now what is supported: https://github.com/voc/media.ccc.de/blob/master/app/controllers/api/recordings_controller.rb

**HD:** I set this flag from the old vendor mime types. So it should be exactly as broken as before? We'd have to run ffprobe on all files to get their dimensions, so we can deduce quality from that. There might be more information in the VOC tracker for congress videos.

**Comment by derpeter** [comment]
@manno i would prefer a tracker independent solution, there is much more content on media then the tracker knows about and even if we tie many things to the tracker i think keeping media working with out it is good for the community

**Comment by manno** [comment]
@derpeter Since we only support different languages for 31c3, I thought using tracker data might be safer than to use a regex on the file name.

**Comment by saerdnaer** [comment]
The event (aka lecture) now has an original_language field, does this resolve your problems @TobiX?

**Comment by saerdnaer** [comment]
Please reopen if this is still an issue for you.
