### ISSUE TITLE
Revise/redesign player page

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctoweb#64]
Currently the download tab looks similar to this:
![temp](https://cloud.githubusercontent.com/assets/40266/13094013/8a7c6b96-d508-11e5-9610-ff17352cc8dd.png)

the folder in which a recording is stored at might also trigger display of an hd or sd flag simular to the language. Mookup:
![temp2](https://cloud.githubusercontent.com/assets/40266/13094402/b1539c9c-d50a-11e5-9731-d60201ec53ec.png)

**Comment by manno** [comment]
Just a quick note, we also have a 'high'/'low' flag on recordings, which might indicate the quality settings, baseline profile, 'intention of the encoder'.

If anyone could come up with a better UI, copying the white boxes was never intended - just a quick hack for 32c3, that would be great :)

**Comment by MaZderMind** [comment]
Auf dem Geekend wurde beschlossen, das Download-Tab grundsätzlicher zu überarbeiten. Dazu wurden  folgende Überlegungen getätigt:

- Ein Nutzer besucht eine Vortrags-Seite
- Er sieht keine Tabs mehr
- Unter Titel und Untertitel folgt direkt der Video-Player
- Darunter folgt der About-Block, wie gehabt
- Darunter folgen die Share-Funktionen
- Darunter folgt der Download-Bereich

- Im Download-Bereich wird nach Video und Audio unterschieden
- Es werden nur die Recordings mit der maximalen Anzahl von Sprachen angezeigt
- Nach den Videos kommt ein Info-Block zu mehreren Sprachen, wenn die gewählten Recordings mehrere Sprachen enthalten
- Darunter folgt der Audio-Download-Block, in dem alle Audio Recordings in allen Sprachen angezeigt werden. Die Buttons können mit Flaggen oä. identifiziert werden.
- Darunter folgt der Subtitles-Download als Drop-Down für jede Sprache
- Daneben kann ein Slides-Download-Button erscheinen

**Comment by jjeising** [comment]
Mockup:
![2-video player](https://cloud.githubusercontent.com/assets/40333/14767536/3bf5b6a8-0a28-11e6-8489-aeff439dc345.png)

**Comment by saerdnaer** [comment]
Macht es Sinn einzelne Elemente wie z.B. diesen "multiple-languages"-Hinweis auch jetzt schon einzubauen, oder kommt das neue Design eh demnächst?

**Comment by MaZderMind** [comment]
@saerdnaer der PR ist jetzt soweit fertig und wird in Kürze™ ausgerollt werden

**Comment by MaZderMind** [comment]
Vergessenes TODO: Der Audioplayer ist im aktuellen Design nicht mehr drin und sollte auch aus dem Code ausgebaut werden. Ggf. existiert er zukünftig nur noch im Kontext von #96 für Audio-Only Inhalte
