### ISSUE TITLE
Umbau Recent-Videos/-Events

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctoweb#74]
## To be discussed.

**Ideen:**
Recent Events ->
- auf die Startseite
- Titel anzeigen
- 2-3 Recordings auflisten (Anzahl in Klammer)

News nur anzeigen wenn neuste News <14 Tage alt
Recent Recordings -> unter "Recent Videos" anzeigen

**Comment by jjeising** [comment]
Draft homepage:

![1-home](https://cloud.githubusercontent.com/assets/40333/14767756/d8f47f3e-0a2d-11e6-9b60-f1c31bf54321.png)
