### ISSUE TITLE
CDN DOWN? 

### ISSUE THREAD

**Issue by altf4arnold** [voc/voctoweb#741]
Hello,

It seems that your CDN is down? (I can't get any media to play on any network at this precise moment)...

**Comment by Kunsi** [comment]
Thanks for reporting, the issue was fixed about two hours ago.

(My gut feeling is that this is not the right place to report such issues, but i can't think of a better place to do so :/)

**Comment by altf4arnold** [comment]
Which is why I reported here 😜
