### ISSUE TITLE
Broken link on specific media page

### ISSUE THREAD

**Issue by aspenmayer** [voc/voctoweb#745]
The [link to the Fahrplan](https://fahrplan.das-sendezentrum.de/rc3/talk/RNFEGT/) on [this page](https://media.ccc.de/v/rc3-520410-funkwhale_and_the_importance_of_decentralized_podcasting) is broken: 502 Bad Gateway

From what I can tell, the correct link should be:

[https://rc3.world/rc3/event/rc3-520410-funkwhale_and_the_importance_of_decentralized_podcasting/](https://rc3.world/rc3/event/rc3-520410-funkwhale_and_the_importance_of_decentralized_podcasting/)

There may be more broken links to rc3 Fahrplan on other media.ccc.de talks from that event, but I have not looked into this, so I can only ask that someone more familiar with the site have a more thorough look.

Hope that helps.

**Comment by saerdnaer** [comment]
Sadly the URL to the original fahrplan source is correct, but as far as I am informed the old Sendezentrum pretalx won't come back. You can install an archive.org browser plugin which would redirect you to https://web.archive.org/web/20210921164231/https://fahrplan.das-sendezentrum.de/rc3/talk/RNFEGT/
