### ISSUE TITLE
StateOfTheMap conference logo missing

### ISSUE THREAD

**Issue by cweiske** [voc/voctoweb#749]
https://api.media.ccc.de/public/conferences lists "State of the Map 2024" with a `logo_url` of 
https://static.media.ccc.de/media/events/sotm/2024/sotm_2024-logo.svg - this one gives a 404.

Same for the conference details API endpoint https://api.media.ccc.de/public/conferences/sotm2024

Other missing logos:
- [x] https://static.media.ccc.de/media/events/dhcp/2024/dhcp24-logo.png
- [x] https://static.media.ccc.de/media/events/vcfb/2024/logo.png

**Comment by jbeyerstedt** [comment]
DHCP 2024 is "fixed" by specifying a specific logo path in the backend. API results should update in the next minutes to point to the default icon.
