### ISSUE TITLE
Issues with the CDN?

### ISSUE THREAD

**Issue by Tilltheman** [voc/voctoweb#754]
I currently cannot load videos on the web browser and if I click the link for downloads I get a 404 for the CDN. With the browser as well as wget. Are there issues known? Example:

```
$ wget https://cdn.media.ccc.de/congress/2024/h264-hd/38c3-598-deu-eng-fra-Wir_wissen_wo_dein_Auto_steht_-_Volksdaten_von_Volkswagen_hd.mp4
--2024-12-30 16:04:48--  https://cdn.media.ccc.de/congress/2024/h264-hd/38c3-598-deu-eng-fra-Wir_wissen_wo_dein_Auto_steht_-_Volksdaten_von_Volkswagen_hd.mp4
CA-Zertifikat »/etc/ssl/certs/ca-certificates.crt« wurde geladen
Auflösen des Hostnamens cdn.media.ccc.de (cdn.media.ccc.de)… 2001:67c:20a0:e::176, 185.106.84.47
Verbindungsaufbau zu cdn.media.ccc.de (cdn.media.ccc.de)|2001:67c:20a0:e::176|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2024-12-30 16:04:48 FEHLER 404: Not Found.
```
The stream is still working though.

**Comment by Tilltheman** [comment]
![20241230_16h16m33s_grim](https://github.com/user-attachments/assets/f0761cf0-625d-4231-a607-478e1006b34f)
![20241230_16h16m45s_grim](https://github.com/user-attachments/assets/0f920a70-4030-4302-9e6e-57e3133cfa61)
Some screenshots ;-)

**Comment by hack03er** [comment]
@Tilltheman I have the same issue. If you need access right away i can recommend the mirror at https://ftp.fau.de/cdn.media.ccc.de

**Comment by Tilltheman** [comment]
Thanks for confirming it was not a me-issue and the link to FAU's ftp. In the meantime it seems to be working again, so thanks to whoever fixed it. Closing the issue.

**Comment by QbDesu** [comment]
Yeah our CDN master servers are being DDOSed at the moment, things should fix themself soon.
