### ISSUE TITLE
Search result previews should be clickable

### ISSUE THREAD

**Issue by florolf** [voc/voctoweb#98]
The result previews in the search should be clickable. There _is_ an <code>&lt;a&gt;</code> tag, but it gets covered by the duration-container div.

**Comment by MaZderMind** [comment]
For reference: the reason for this convoluted construct is, that the speaker-names should be clickable separately, so we can't wrap the whole thing in a single a-tag, because nesting a-tags inside each other is not supported. fix ahead.
